### ISSUE TITLE
Console Client lagging or out of sync

### ISSUE THREAD

**Issue by Winninq** [ORelio/Minecraft-Console-Client#490] opened 2018-06-07 01:40 UTC
Kind of hard to explain, but every time I start the console client it starts "lagging", or going out of sync with the server. It still lets me use commands and send messages just fine, but it doesn't show it in the console. This is very annoying as it pretty much breaks the AntiAFK and AutoRelog and stops them from performing their functions (eg. bot will no longer teleport to a specific location every 60 seconds). Then after a few minutes, it will always either crash the process, time out from the server (AutoRelog still won't work to log it back in), or fix itself and sync back up with the server (rarely happens).

Here's an example of it happening, as like I said it's pretty hard to explain:
 - https://youtu.be/qduhLht5ZjE

Would appreciated it if I could get a response soon, thanks.

**Comment by ORelio** [comment] 2018-07-04 17:56
This might have something to do with your Mono version (see #447)

**Comment by ORelio** [comment] 2018-11-15 20:36
Closing as duplicate of #447.

**Closed by ORelio** 2018-11-15 20:36 UTC

**Comment by Hakonholee** [comment] 2019-05-10 12:38
@ORelio 
This happens to all my console clients, do you know why?
"Connection has been lost.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client."

**Comment by Hakonholee** [comment] 2019-05-10 12:39
Also I can't find my kickmessages.txt file in my console client anymore

**Comment by ORelio** [comment] 2019-05-11 18:06
Only know that it happens more often on Linux/Mac with Mono framework. You may enable AutoRelog with "Connection has been lost" as kick message.

**Comment by Hakonholee** [comment] 2019-05-12 09:51
Okay, but my AutoRelog is now /server magma . Can it be 2 different things
at once?

lør. 11. mai 2019 kl. 20:06 skrev ORelio <notifications@github.com>:

**Comment by ORelio** [comment] 2019-05-12 12:05
AutoRelog does not send commands. Maybe you are talking about ScriptScheduler with OnLogin event. If you need two different behaviors, maybe you'd need to have 2 separate MCC setups, i.e. MCC installed in 2 different directories with different configuration.

**Comment by Hakonholee** [comment] 2019-05-13 06:08
But I can’t find my kickmessages file. On my old comouter I had my
kickmessages file but I got a new computer, downloaded the console client
and now kickmessages is nowhere to be seen.

søn. 12. mai 2019 kl. 14:05 skrev ORelio <notifications@github.com>:

**Comment by ORelio** [comment] 2019-05-13 16:00
Just create it using Notepad. Or take this one: https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/kickmessages.txt

**Comment by Hakonholee** [comment] 2019-05-13 16:18
thanks for the help :)

man. 13. mai 2019 kl. 18:00 skrev ORelio <notifications@github.com>:
