### ISSUE TITLE
[BUG] Connection Error

### ISSUE THREAD

**Issue by zs4** [ORelio/Minecraft-Console-Client#1784] opened 2021-10-05 19:16 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

Any

### Console Client Version

Latest

### Expected Behavior

Starting the MCC and logging in to Server.

### Actual Behavior

It says connecting to Minecraft.net and then this Error Pops up:

Error:
Console Client for MC 1.4.6 to 1.17.1 - v1.17.1 - By ORelio & Contributors
AppVeyor build 526, built on Sat 10/02/2021 from commit eba3091
[MCC] [Settings] Loading Settings from C:\Users\janni\Downloads\MinecraftClient.ini
[MCC] [Translations] No translation file found for en. (Looked 'C:\Users\janni\Downloads\\lang\mcc\en.ini'
[MCC] [Translations] No translation file found for system language (de). (Looked 'C:\Users\janni\Downloads\\lang\mcc\de.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
[SessionCache] Initializing FileSystemWatcher for file: C:\Users\janni\Downloads\SessionCache.ini
No sessions could be loaded from disk
Login :************ (Censored)
Password : <******>                                                                                                     Connecting to Minecraft.net...
Performing request to authserver.mojang.com
System.Security.Authentication.AuthenticationException: Fehler bei SSPI-Aufruf, siehe interne Ausnahme. ---> System.ComponentModel.Win32Exception: Die angeforderte Funktion wird nicht unterstützt
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest(List`1 headers, String host, String& result)
   bei MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost(String host, String endpoint, String request, String& result)
   bei MinecraftClient.Protocol.ProtocolHandler.MojangLogin(String user, String pass, SessionToken& session)
Minecraft Login failed :SSL Error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

### Steps to Reproduce the bug

1. Start MCC
2. Login
3. Enter Server IP
4. Then Error Pops up

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

I tried it on 15-20 Servers same error.

**Comment by Tazahxdxd** [comment] 2021-10-05 19:33
I am having the same issue.
Was fine until yesterday.

**Comment by zs4** [comment] 2021-10-05 19:52
> I am having the same issue. Was fine until yesterday.

Yes, worked fine yesterday but now I have that Issue.

**Comment by TiggyBoy** [comment] 2021-10-05 20:15
Download the newest dev release, it was fixed.

**Comment by ORelio** [comment] 2021-10-05 20:46
Closing as duplicate of #1780.

**Closed by ORelio** 2021-10-05 20:46 UTC
Labels: a:bug
