### ISSUE TITLE
is there anyway to check if the player in the console client has an certain item in there inventory?

### ISSUE THREAD

**Issue by Twi5TeD** [ORelio/Minecraft-Console-Client#575] opened 2018-10-15 13:01 UTC
is there anyway to check if the player in the console client has an certain item in there inventory? 
i wanted a script to sell if a block goes into the players inventory is there anyway of doing that

**Comment by ORelio** [comment] 2018-11-07 21:49
Sorry, inventory is not implemented.

**Comment by Twi5TeD** [comment] 2018-11-07 22:11
would this ever be added?

**Comment by ORelio** [comment] 2018-11-15 19:32
Unfortunately I have no time to work on it myself at the moment. However a contributor could pick up this feature request and implement it.

**Comment by TheSnoozer** [comment] 2018-11-19 02:12
Closing as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/205

**Closed by TheSnoozer** 2018-11-19 02:12 UTC
