### ISSUE TITLE
Player wont physically move.

### ISSUE THREAD

**Issue by teacccc** [ORelio/Minecraft-Console-Client#828] opened 2019-11-17 01:02 UTC
So for my AFK circumstances I need the account on the console client to be moved around by water in the AFK pool I have it in. I have tried messing with the settings and I cant get the account to physically be pushed by water. Any help?

**Comment by Mhowser** [comment] 2019-11-17 02:29
Mcc doesn't have the code for liquids even with terrain movements enabled.

**Comment by teacccc** [comment] 2019-11-17 05:31
So the player cant even be pushed by water in an AFK pool? Do you know any work arounds or alternative programs

**Comment by Mhowser** [comment] 2019-11-17 21:13
Correct, the only thing I can think of is just using the game in the background while you afk. At Least until there is a PR for liquid interaction.

**Comment by ORelio** [comment] 2019-11-24 11:56
Hello, yes, water is not implemented. See #206 .
But you do not really need water for AFKing as you can use ScriptScheduler to periodically run a script that would move the player e.g.
```
move north
sleep 10
move south
```
So that the player periodically moves without using water at all.
Closing the issue as duplicate of #206 😉

**Closed by ORelio** 2019-11-24 11:56 UTC
