### ISSUE TITLE
Bridge chat to IRC

### ISSUE THREAD

**Issue by RoboMWM** [ORelio/Minecraft-Console-Client#138] opened 2016-04-04 05:22 UTC
This is a feature request to enable the client to act as an IRC bot and be controlled from IRC. Although I personally plan to just use it myself in a private ZNC partyline channel, this suggestion could be expanded to bridge all chat from selected channels to the game and back via a client, and controlled only via users with certain permissions in the channel (or hostnames).

This would allow chat to be bridge to an IRC channel on vanilla servers, or servers that try to run as few plugins as possible.

**Comment by ORelio** [comment] 2016-04-04 18:04
Hello,
That's a nice idea but I never poked around with IRC channels. That should however be possible but not really planned unless you could provide some library free C# code for interacting with an IRC server? If the issue is having it working with MCC, there is a bot API you can use for building a ChatBot, these bots can get incoming chat messages and send chat messages so they can then be linked to the IRC handling code.

**Comment by RoboMWM** [comment] 2016-04-04 18:39
Hmm, I haven't ever built an IRC chatbot, but I'll see if that's something I could do.

**Comment by ORelio** [comment] 2016-04-04 21:35
Okay! I can help with integration with the project, it seems fun, but currently I don't really have the time to develop IRC interoperability itself. If I could have some code that connects to the chosen IRC server and allows receiving/sending messages, I could write the ChatBot for Minecraft Console Client that links that to the Minecraft Chat, basically every message that comes out from the Minecraft chat is sent to the IRC server and vice versa -- the only gotcha beign ignoring messages sent by the bot itself to avoid infinite sending loops :)

**Comment by RoboMWM** [comment] 2016-04-19 06:57
Haven't had time to look into this yet (perhaps in a couple weeks I will), but here's some stuff I found a couple days ago, if it's any help: http://www.c-sharpcorner.com/UploadFile/pasihavia/IrcBot11222005231107PM/IrcBot.aspx

**Comment by MattCowley** [comment] 2017-05-04 13:59
Hey just to hop onto this, I don't know an C# but I'm happy to learn. Could you (@ORelio) show me how to capture chat and send messages to chat via script? I can work from there myself :)

**Comment by RoboMWM** [comment] 2017-05-04 15:16
>via script

wat

**Comment by MattCowley** [comment] 2017-05-04 16:08
Isn't there a way to hook custom C# into the minecraft console client?

**Comment by ORelio** [comment] 2017-05-04 16:28
There is. See [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script-with-chatbot.cs) you can override chatbot methods, see [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/ChatBot.cs). Also, when outside ChatBot (in a script's main section), the API this located in [CSharpRunner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/b848460a5ccf5f2d05db575b74388e3e95d7177c/MinecraftClient/CSharpRunner.cs#L181). Good luck :wink:

**Comment by MattCowley** [comment] 2017-05-04 16:49
Is there a command to end a script without rebooting the console client?

**Comment by ORelio** [comment] 2017-05-04 17:18
Currently, no, although the script can unload itself by exiting early.
Moreover, if you load a ChatBot from the script, then the ChatBot persits after the script has ended.
The same way, ChatBot can unload themselves.

**Comment by MattCowley** [comment] 2017-05-04 17:29
I've done UnloadBot(); How do I completely end the script at that point too?

**Comment by ORelio** [comment] 2017-05-04 17:37
Let's assume you have `sample-script-with-chatbot.cs`:
1. You launch the script: `/script sample-script-with-chatbot.cs`
2. The script loads a chatbot: `ExampleBot`
3. The scripts ends
4. The ChatBot stays loaded
5. Assuming the ChatBot calls `UnloadBot()` then everything is unloaded

**Comment by MattCowley** [comment] 2017-05-06 09:52
Brilliant! One final question, within the script how do I include a library thing. I tried `using System.Net;` but that errored.

**Comment by ORelio** [comment] 2017-05-06 10:02
`using` is currently not supported as code is generated [this way](https://github.com/ORelio/Minecraft-Console-Client/blob/b848460a5ccf5f2d05db575b74388e3e95d7177c/MinecraftClient/CSharpRunner.cs#L69) in CSharpRunner.

**Comment by MattCowley** [comment] 2017-05-06 10:10
Is it possible to supply a custom CSharpRunner or additional things for using?

**Comment by ORelio** [comment] 2017-05-06 15:11
What? Simplest way would be using fully qualified names or adding your own `using` in CSharpRunner.

**Comment by MattCowley** [comment] 2017-05-06 15:48
I really don't know much C#, what would be the fully qualified name instead of `using System.Net;` and then `HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);`?

**Comment by ORelio** [comment] 2017-05-06 16:05
````
System.Net.HttpWebRequest request = (System.Net.HttpWebRequest)WebRequest.Create(url);
````

**Comment by Pokechu22** [comment] 2017-05-06 16:05
```c#
System.Net.HttpWebRequest request = (System.Net.HttpWebRequest) System.Net.WebRequest.Create(url);
```

**Comment by MattCowley** [comment] 2017-05-06 16:05
Another question, sorry. What's the best way to make a continual loop in the chatbot?

**Comment by ORelio** [comment] 2017-05-06 16:06
Better twice than once 😂

**Comment by ORelio** [comment] 2017-05-06 16:07
@MattCowley There is an [Update()](https://github.com/ORelio/Minecraft-Console-Client/blob/dda2ce293cb1edd252550993627700e47932a26e/MinecraftClient/ChatBot.cs#L104) method you can override.

**Comment by MattCowley** [comment] 2017-05-06 16:10
Fantastic! I've got as far as logging chat to a database via a get request. Now just to get messages from the database for chat posting!

**Comment by MattCowley** [comment] 2017-05-06 16:24
Ok I've got a bit stuck. Any suggestions as to how to parse a json string @ORelio ?

**Comment by ORelio** [comment] 2017-05-06 16:31
If you really need to parse Json you might want to use this: [Json.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Json.cs) it's main aim is to parse Json chat messages but that might fit your needs.

**Comment by MattCowley** [comment] 2017-05-06 16:42
Sorry i'm not that good with this, could you give me an example of how to pass a json string and get back an array?

**Comment by ORelio** [comment] 2017-05-06 16:56
With fully qualified names:
````C#
string jsonInput = //your json
MinecraftClient.Protocol.Handlers.JsonData data = MinecraftClient.Protocol.Handlers.Json.ParseJson(jsonInput);
if (data.DataType == MinecraftClient.Protocol.Handlers.Json.JSONData.DataType.Array)
{
    foreach (MinecraftClient.Protocol.Handlers.Json.JSONData item in data.DataArray)
    {
        if (item.DataType == MinecraftClient.Protocol.Handlers.Json.JSONData.DataType.Object)
        {
            string field = item.Properties["fieldName"];
            //...
        }
    }
}

**Comment by MattCowley** [comment] 2017-05-06 17:28
I'm getting this: https://gyazo.com/565a0933382392502d8e93285db9ee0e

**Comment by ORelio** [comment] 2017-05-06 17:37
````C#
MinecraftClient.Protocol.Handlers.Json.JsonData
````
`data.DataArray` *is* an array so do as you prefer to.

**Comment by MattCowley** [comment] 2017-05-06 17:39
Ah should've spotted that. Getting this now :/ https://gyazo.com/b5707a2289a1ae515596a1c044dcf9e7

Cool.

**Comment by MattCowley** [comment] 2017-05-06 18:48
@ORelio ?

**Comment by ORelio** [comment] 2017-05-06 19:12
Indeed, that class is not public. Moving it in main package with `public` modifier. Use latest [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
Also now, you don't need fully qualified names anymore, so
````C#
string jsonInput = //your json
Json.JsonData data = Json.ParseJson(jsonInput);
if (data.DataType == Json.JSONData.DataType.Array)
{
    foreach (Json.JSONData item in data.DataArray)
    {
        if (item.DataType == Json.JSONData.DataType.Object)
        {
            string field = item.Properties["fieldName"].StringValue;
            //...
        }
    }
}
````
...should work. More readable, isn't it?

**Comment by MattCowley** [comment] 2017-05-06 20:15
99% done, how do i get the username of the current logged in account?

**Comment by Pokechu22** [comment] 2017-05-06 20:17
Per #249: use <code lang="csharp">Settings.Username</code>.

**Comment by MattCowley** [comment] 2017-05-06 20:35
Right I've got a mc/discord bot working. If people wanna message me for snippets of code let me know!

**Comment by ORelio** [comment] 2017-05-06 22:03
I'd gladly include your script in the provided sample scripts if you wish to :smile:

**Comment by MattCowley** [comment] 2017-05-07 07:35
Hey @ORelio , so I'm adding a layer of auth kinda, due to the server using nickname, I need to run /realname and then capture the return of that command whilst inside GetText(), any ideas?

**Comment by MattCowley** [comment] 2017-05-07 11:26
Also can i specify a script to launch via the command line like account and ip?

**Comment by ORelio** [comment] 2017-05-07 12:10
There is no magic way to get output for a specific command. The server sends a stream of packets, including text messages to print in chat. There is no way to determine if the line is some command output, and of course I'm not even speaking of tying it to a command previously sent. You're going to need a [ChatBot](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/ChatBot.cs) ([sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script-with-chatbot.cs)), use [SendText](https://github.com/ORelio/Minecraft-Console-Client/blob/a52fb6135817521c6749b3abeb38563947f807b2/MinecraftClient/ChatBot.cs#L140), then watch for command output in [GetText](https://github.com/ORelio/Minecraft-Console-Client/blob/a52fb6135817521c6749b3abeb38563947f807b2/MinecraftClient/ChatBot.cs#L105) and try matching every received message to determine if it contains output for that command. I'm don't really recommend this approach, directly using nicknames would be way easier.

You need to use [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L178) to launch scripts on startup. See also [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-tasks.ini).

**Comment by MattCowley** [comment] 2017-05-07 12:37
Ah ok. That's annoying. I needed usernames as I can't generate UUIDs from nicknames.

**Comment by ORelio** [comment] 2017-05-07 12:57
Well, you *can* resolve nicknames, just, that'll require much work. :wink:
I'd advise the following:

 - Store messages in a queue (Nickname + Text)
 - Store nickname -> realname mappings in a table (Dictionary)
 - Store nickname -> realname mapping requests in a queue
 - Store current mapping request in a variable
 - In Update()
    - If there is no current mapping request:
        - if there are mapping requests awaiting:
            - dequeue first mapping request and send /realname <nick>
        - else:
        - resolve all awaiting messages to realname and process them
 - In GetText()
    - If there is a realname response, get nickname from variable and store nick -> real mapping in table, set current request back to null
   - If this is a chat message, store nickname and message in the processing queue

Something like that. Good luck.

**Comment by Pokechu22** [comment] 2017-05-07 16:05
Note that both of these are only issues on craftbukkit/spigot, as on vanilla you _can_ tell the difference between chat messages and command outputs, and you _can_ hover over a player's name to get their UUID.  It just doesn't work in craftbukkit (I've been trying to fix it, but it's fairly complicated)

**Comment by ORelio** [comment] 2017-05-08 14:56
Well as CraftBukkit was designed for old-style chat messages (MCC is also designed this way), I guess that passing new-style json messages through the Bukkit APIs would break quite a lot of plugins.

**Comment by koelkast99** [comment] 2017-11-16 15:21
@MattIPv4 @ORelio 
hello i was looking into console client and specially the blockwatch feature its works great but is there away to instead of letting it beep let it send a message to discord through a bot??
i have no experience with codeing or anything!

**Comment by Pokechu22** [comment] 2017-11-16 17:31
You'd need to find an API client for discord that is usable from C#.  It would be possible, but it'd take a bit of setup (and I haven't done anything like that before).

If you want more help, create a new issue -- that's a more complicated problem that would be best discussed in its own thread.

**Comment by koelkast99** [comment] 2017-11-16 18:51
okeey thank you i will take a look when i get stuck i will make a new issue. thanks

**Closed** 2020-08-03 08:01 UTC
