### ISSUE TITLE
Lamp Detector Skype Or Discord Alert?

### ISSUE THREAD

**Issue by SpikeThatMike** [ORelio/Minecraft-Console-Client#400] opened 2018-03-10 13:31 UTC
I'm all new to coding but i'm wondering if there is any way when  LogToConsole("Lamp at " + lampLoc + " is currently turned OFF !!!"); is triggered to send a message to Skype or Discord
If someone could help it would be great.

**Comment by ORelio** [comment] 2018-03-23 22:41
You can use the [discord API](https://discordapp.com/developers/docs/intro) in your bot. There is no built-in support.

**Comment by ORelio** [comment] 2018-03-23 22:42
I'm closing this issue as duplicate of #258 - feel free to disscuss it further in that issue instead :wink:

**Closed by ORelio** 2018-03-23 22:42 UTC
