### ISSUE TITLE
Minecraftclient.exe shuts down after logged in  - "OverflowException: VarInt too big"

### ISSUE THREAD

**Issue by Nowhereman23** [ORelio/Minecraft-Console-Client#432] opened 2018-05-03 20:00 UTC
I have gotten this problem recently.

The error message, is "System.OverflowException: VarInt too big", and then a lot of "error-pointers" under that error. 

The servers I login to, is running 1.12, paper (or paperclip) if that matter. It seems to have started recently. 2 of 4 servers I use to login to, give this error (1 of them started give the error couple of days ago, and all of them is using paperclip).

I have tested MCC/Vanilla/None as settings in ini-file, and the same error happen, also 1.12 version (if setting it lower, the server doesn't allow me to login). I have made sure I use the latest MinecraftClient.exe-version.

After this error, I can still receive some very few initial server-to-user-messages, sometimes it catch a chat from a player within a very short time after the error, and then minecraftclient.exe shuts down.

Imgur-link to console with error messages:
https://i.imgur.com/8CzsB08.png

There is an older issue with similar error (or the same error?), and reference it from here. (And ty for reply in that thread).

https://github.com/ORelio/Minecraft-Console-Client/issues/84

Thanks for a great application.

**Comment by ORelio** [comment] 2018-05-05 08:58
Thanks for your detailed report. I think this bug is different from #84. If your server is guaranteed to crash MCC, the easiest way for me to diagnose this would be to try joining that server from MCC running in a debug session. Would you mind providing the IP address of the problematic server?

**Comment by Nowhereman23** [comment] 2018-05-07 22:48
No problem. The server in question is 'constantiam.net'.

**Comment by ORelio** [comment] 2018-05-08 16:30
Joined that server with latest dev version and terrain and movements enabled, but could not trigger the crash. Is there anything I need to do in order to trigger it? :thinking:

**Comment by Nowhereman23** [comment] 2018-05-08 22:15
Oh ok..  now I know what I did wrong. 

First I thought this was strange. I downloaded the latest version right now (Minecraft Console Client v1.12.2 DEV), and still get the crash. I tested to run it in a new folder, and generated a fresh ini-file, with no other info in it than login/serverip. 

But I had not enabled terrainandmovement and tested out the other settings, :O and, that did the trick on this server "assumed in some stupid idea that all server use same settings". 

Sorry for taking your time. Now it works totally great. :)
Thanks for giving me the direction.. :P

**Comment by ORelio** [comment] 2018-05-08 22:30
Actually, I'm enabling `terrainandmovements` because this setting enables a set of features related to terrain handling that may contain bugs so that's needed when trying to reproduce a crash. Enabling this setting should not suppress any issue... just retried with `terrainandmovements=false` and nothing happens on my side, it just works. I'm even more puzzled, now :confused:

**Comment by Nowhereman23** [comment] 2018-05-09 12:16
Oh well, I have strange things going on here..

I first rechecked again, and it was still the same thing for me (terrain=true works and terrain=false still not working), switching between them. About 3 times perhaps, I got this error message ("varint too big") when terrain=false.

Then I thought I would enable debug-messages, and send it to text-files via "minecraftclient >output.txt" (one output for enabled and one output for disabled terrainandmovement). And... well.. then I got an error with that, saying "Referense (Handle) is wrong/illegal/not allowed (or similar. I'm trying to translate because I have local language). 

But perhaps blocking output to console and direct it to txt-file create an error itself, so I stopped trying that and thought I should mark the text from console and copy-paste that way instead. 

And now suddenly... I succeed to login with no crash when terrain is set to "false". And it have been working since, and I don't know what made it work except when trying to send to "minecraftclient.exe >out.txt" and now I don't have any error at all at normal start, no matter if I choose terrain false or terrain true.

I had this error always with this server. (although with terrain=false) and now I don't. 

I have tested to login to several servers so that token changes, and then back to this server, switched back and forth between false/true at terrain, delete cache-settings/language-folder, use memory instead of disk, and it still works with terrainmovement=false. I don't know how to "create this error" again.

That's the strange thing.

**Comment by ORelio** [comment] 2018-05-09 21:27
There is still a possibility that the server was actually sending invalid data, looking at the stack trace, an invalid number was read when trying to read packet length or packet ID (as per [protocol specs](http://wiki.vg/Protocol#Packet_format)). The official client would also disconnect and show an error message if that happens.

**Comment by Nowhereman23** [comment] 2018-05-10 14:35
Yes, probably, I have no more input. It works flawless now.

**Comment by ORelio** [comment] 2018-05-10 14:42
OK, I'll close the issue but you can reopen it if you find a way to reproduce 😉

**Closed by ORelio** 2018-05-10 14:42 UTC
