### ISSUE TITLE
Interact with beds (sleeping)

### ISSUE THREAD

**Issue by ramboi234** [ORelio/Minecraft-Console-Client#1315] opened 2020-11-06 03:14 UTC
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
A feature request should contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any alternative solutions or features you've considered.
* If applicable, add screenshots to help explain your request

I already look at [autolook script](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/AutoLook.cs), but idk how set entity to bed EntityType.Item.bed maybe?, and how to call right click function?, I don't think its possible to check its day or night, so I will just set interval on it, can someone help me? I don't know how to code

**Comment by ReinforceZwei** [comment] 2020-11-06 03:24
MCC doesn't support sleeping.

**Comment by ramboi234** [comment] 2020-11-06 03:30
ahhh, alright thanks

**Comment by Nekiplay** [comment] 2020-11-08 06:53
> ahhh, alright thanks

Use method placeblock on bedblock

**Comment by ORelio** [comment] 2021-05-21 18:59
Closing this request as duplicate of #727

**Closed by ORelio** 2021-05-21 18:59 UTC
Labels: a:enhancement, in:entity-handling, waiting-for:contributor
