### ISSUE TITLE
I can not make it detect me when it's public or private

### ISSUE THREAD

**Issue by Carlosca1998** [ORelio/Minecraft-Console-Client#391] opened 2018-02-14 18:20 UTC
Someone helps me and tries in many ways but I can not find the chat format when it is a public or private message.

I would like to know if you could help me solve it.

Here is a picture of the chat the arriva is the private and the below the public.
https://i.imgur.com/d6VTrA7.png

Here is another photo but taken from the console client.
https://i.imgur.com/6PvYmk8.png
https://i.imgur.com/p96BxbO.png

**Comment by TheSnoozer** [comment] 2018-11-19 22:41
Duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/393#issuecomment-370158058

**Closed by TheSnoozer** 2018-11-19 22:41 UTC
Labels: a:question, in:chat-format-regex
