### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by Skybird77** [ORelio/Minecraft-Console-Client#613] opened 2018-12-21 22:27 UTC
Whenever I connect to the server I'm connected to the hub then I do the command to travel to the actual server. But after I do that console client crashes and gives me this error: 

Unhandled Exception: System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextVarInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

It lets me connect from a different account though and I have tried changing the password to see if that would fix it.

**Comment by TheSnoozer** [comment] 2018-12-21 22:30
Seems related to https://github.com/ORelio/Minecraft-Console-Client/issues/379

can you post your config (make sure it does not have your credentials) and the server you are trying to connect to?

**Comment by Skybird77** [comment] 2018-12-21 22:32
The minecraftclient.ini?

**Comment by Skybird77** [comment] 2018-12-21 22:34
> Seems related to #379
> 
> can you post your config (make sure it does not have your credentials) and the server you are trying to connect to?

The minecraftclient.ini ?

**Comment by TheSnoozer** [comment] 2018-12-21 22:58
yes the `MinecraftClient.ini`

**Comment by Skybird77** [comment] 2018-12-21 23:00
[MinecraftClient.zip](https://github.com/ORelio/Minecraft-Console-Client/files/2704512/MinecraftClient.zip)
thats minecraftclient.ini i had to zip it since i cant send .ini files

**Comment by Mhowser** [comment] 2018-12-22 00:59
For future reference you can just rename it from .ini to .txt

**Comment by TheSnoozer** [comment] 2018-12-23 14:00
I can not reproduce the problem on my side.

1. What operating system do you have? Windows?
2. What is the contents of the ` changingscripts=ban.ini` file?
3. What happens if you change the `=` to a `_` inside the filename? (e.g. the file becomes `changingscripts_ban.ini` in the config and on the file system)

**Comment by Skybird77** [comment] 2018-12-25 02:54
im using windows 10 
the contents :
# Minecraft Console Client
# ScriptScheduler Tasks
# Example config file

# Structure of a task: [Task] Followed by triggers and other settings.
# The example below contains all the possible fields for a task
# Time is HH:mm format, several different hours can be provided

[Task]
triggerOnFirstLogin=true
triggerOnLogin=true
triggerOnTime=true
triggerOnInterval=false
timeValue=19:30
timeValue=08:10
timeInterval=0
script=reconnect.txt

# Another minimal example: some properties may be omitted
# This is highly recommended for improving task readability

# Of course, the tasks file can contain as much tasks as you want.
# Another example tiggered on logging in and every night at midnight:

# Example of task occuring every 30 seconds
# Could be used for making a custom antiAFK procedure

# Enjoy!
# - ORelio

the same result happens

**Comment by TheSnoozer** [comment] 2019-03-17 02:07
I'm closing this as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379 since I'm actually not sure if there is any benefit of keeping the same set of issues around. Sadly not sure what causes it :/

**Closed by TheSnoozer** 2019-03-17 02:07 UTC
Labels: a:bug, on:windows, rejected:duplicate, waiting-for:more-info
