### ISSUE TITLE
Minecraft Console Client For Android 

### ISSUE THREAD

**Issue by yougeshlama** [ORelio/Minecraft-Console-Client#1407] opened 2021-01-09 17:56 UTC
This will help many people who afk 24/7 for minecraft farms.
As you know we can't always open our computer for 24/7 for afk.So,It would be easy if you make minecraft console client for Android platform also it will easy to afk 24/7 and it will save some electricity also 😂😂
I hope you like this idea.

**Comment by ORelio** [comment] 2021-01-09 18:12
This is not trivial to do, as MCC is programmed in C# whereas Android apps are made in Java.
I'll close this request as duplicate of #1000 😉

**Closed by ORelio** 2021-01-09 18:12 UTC
Labels: a:enhancement, a:new-feature

**Comment by XIAYM-gh** [comment] 2021-02-03 06:01
It's easy to run on Android devices.
You need "AnLiunx" and "Termux", start Termux and install "debian" and "xfce4 desktop",
when you finish it, run command:
./star*
apt update
apt install mono-devel
After that, download (wget) MinecraftClient.exe from some way (such as FTP server on smartphones)
and run this command:
mono MinecraftClient.exe

Have fun ;)

**Comment by XIAYM-gh** [comment] 2021-02-03 06:16
But I think it's not good to run .NET programs on Termux, I think it's too lag. 
Oh, I think you can install a package, its name's "Screen".
If you use Termux's default console, when it disconnected from the server,
you will see something like:
_You chose...
>       (Command prompt here)
Server Version..._
(My English isn't good, so I maybe write something wrong.)

**Comment by ReinforceZwei** [comment] 2021-02-03 06:24
@XIAYM-gh It would be appreciated if you could consider writing a detailed guideline on how to run MCC with Android device.

**Comment by XIAYM-gh** [comment] 2021-02-03 08:45
emm, yeah,I want to do that, but I can't took screenshot in Termux, sorry.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ReinforceZwei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月3日(星期三) 下午2:24
收件人:&nbsp;&quot;ORelio/Minecraft-Console-Client&quot;<Minecraft-Console-Client@noreply.github.com&gt;;
抄送:&nbsp;&quot;XIAYM&quot;<xiaym123@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ORelio/Minecraft-Console-Client] Minecraft Console Client For Android  (#1407)
