### ISSUE TITLE
enabling terrainmovement crashes the client upon starting it! 

### ISSUE THREAD

**Issue by Saman258** [ORelio/Minecraft-Console-Client#309] opened 2017-08-24 10:53 UTC
terrainandmovements=false #uses more ram, cpu, bandwidth
I changed this to
terrainandmovements=true #uses more ram, cpu, bandwidth
but it makes the client crash after starting it

**Comment by ORelio** [comment] 2017-09-09 15:14
Hello,

Could you set `debugmessages=true` in your configuration file and post full output? Redact authentication data and passwords, if any, before posting. Thanks.

If MCC closes instantly (on Windows) please open a console windows (easiest: Shift+RightClick on the folder containing MCC > Open console here) then type MinecraftClient.exe to launch it.

**Comment by TheSnoozer** [comment] 2019-09-20 19:06
I also would suggest to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try if the problem is still present. In case the client crashes with the `debugmessages=true` enabled post any error messages that might appear.

**Comment by ORelio** [comment] 2019-12-19 18:43
Closing this report as it is quite old and does not contain enough info.

**Closed by ORelio** 2019-12-19 18:43 UTC
Labels: a:bug, rejected:invalid, waiting-for:more-info
