### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by CGsama** [ORelio/Minecraft-Console-Client#672] opened 2019-03-16 05:25 UTC
I dont know how this error come from, tried different pc all gives same error, but resolved after connect server by minecraft game client.

No sessions could be loaded from disk
You chose to run in offline mode.
Success. (session ID: )
Using Minecraft version 1.13 (protocol v393)
Translations file loaded.
Version is supported.
Logging in...
Server is in offline mode.
Server was successfully joined.
Type '/quit' to leave the server.
HIM joined the game

Unhandled Exception: System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextVarInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TheSnoozer** [comment] 2019-03-17 02:08
I'm closing this as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379 since I'm actually not sure if there is any benefit of keeping the same set of issues around. Sadly not sure what causes it :/

**Closed by TheSnoozer** 2019-03-17 02:08 UTC
Labels: rejected:duplicate
