### ISSUE TITLE
Inventory Handling

### ISSUE THREAD

**Issue by LunarCC1** [ORelio/Minecraft-Console-Client#1549] opened 2021-04-22 12:44 UTC
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

---
## Describe your problem
Present a concise description of the problem to be addressed by this feature request. 
Would it be possible to add 1.8.9 support for inventory handling, it would be good if you could add that.

---
## Suggest a possible solution
A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
I would like to make 1.8.9 support for inventory handling.

---
## Screenshot to help explain your request (If applicable)

**Comment by ORelio** [comment] 2021-04-22 17:21
Possible duplicate of #997

**Closed** 2021-04-23 21:13 UTC
Labels: a:enhancement, in:inventory-handling, rejected:duplicate
