### ISSUE TITLE
Minecraft Login Failed : SSL Error

### ISSUE THREAD

**Issue by jcodyparker** [ORelio/Minecraft-Console-Client#1782] opened 2021-10-05 06:25 UTC
Works fine playing the game on the Minecraft launcher, won't log in anymore on Console Client. Even tried deleting all config and making a new console client with everything default, still does the same thing.

![image](https://user-images.githubusercontent.com/90956620/135971130-e7d48294-b704-4111-89c0-86d258c77ba0.png)

**Comment by DemonAKALilKid** [comment] 2021-10-05 06:27
isn't this a clone of #1781 ?

**Comment by jcodyparker** [comment] 2021-10-05 06:47
> isn't this a clone of #1781 ?

ah ok didnt see others were having the same issue

**Comment by ReinforceZwei** [comment] 2021-10-05 07:55
Closing as duplicate of #1780.

**Closed** 2021-10-05 07:55 UTC
