### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by ExplodingTacos** [ORelio/Minecraft-Console-Client#452] opened 2018-05-24 00:35 UTC
Issue 451 has not really said any fixes for this or they were talking in code or something.  Is MCC useless now? Is there a way to resolve it? When will it be fixed?

Thank you

Tacos

**Comment by Pokechu22** [comment] 2018-05-24 00:37
It should be fixed if you update.

**Comment by ExplodingTacos** [comment] 2018-05-24 00:46
when?

**Comment by Pokechu22** [comment] 2018-05-24 00:54
As of commit a75710b.  You can get the latest build [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by HexedHero** [comment] 2018-05-24 13:10
Use the newest version, there was a fix today!

**Comment by ORelio** [comment] 2018-05-24 17:11
Seems like a duplicate of #451. So yes, the issue _is_ resolved, just update your console client :wink:

**Closed by ORelio** 2018-05-24 17:11 UTC
