### ISSUE TITLE
Remotecontrol doesn't respond to my private chat

### ISSUE THREAD

**Issue by MCwenka** [ORelio/Minecraft-Console-Client#1196] opened 2020-08-12 03:28 UTC
`botowers=Test`

`[ChatFormat]`
`private=^\[(?:[^ ]+ )?([a-zA-Z0-9_]+) -> 我\] (.+)$`

`[RemoteControl]`
`enabled=true`
`autotpaccept=false`
`tpaccepteveryone=false`
I use the latest development build. Then I log in to the server, when I send `/m Bot send hello` to the bot using the Test account.The bot did not respond.

This should be what the BOT receives: `[Test -> 我] send hello`

**Comment by ORelio** [comment] 2020-08-12 07:14
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages

> Minecraft Console Client can parse messages from the server in order to detect private and public messages. This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots. However, for unusual chat formats, so you may need to tinker with the ChatFormat section of the config file. Building regular expressions can be a bit tricky, so you might want to try them out eg on regex101.com

Usernames in Chinese are not standard Minecraft usernames. You need to adjust the regex.

**Comment by Oopas** [comment] 2020-08-12 09:21
The user name of bot is "Bot", not Chinese...
It's just "我" instead of "me" after a private chat.I guess this is caused by a plug-in on the server.
It looks like it's right after testing the site.

![6613073f635a3ef8](https://user-images.githubusercontent.com/69417818/89997002-1c9a6980-dcbe-11ea-9083-a56d58286b42.jpg)

This is the message that bot received:

![3ebba933d3d1aa1b](https://user-images.githubusercontent.com/69417818/89998098-ac8ce300-dcbf-11ea-9408-4fab3d251367.jpg)

But the BOT still didn't respond😣

**Comment by Oopas** [comment] 2020-08-12 09:27
> https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
> 
> > Minecraft Console Client can parse messages from the server in order to detect private and public messages. This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots. However, for unusual chat formats, so you may need to tinker with the ChatFormat section of the config file. Building regular expressions can be a bit tricky, so you might want to try them out eg on regex101.com
> 
> Usernames in Chinese are not standard Minecraft usernames. You need to adjust the regex. And test it on regex101 🙂

The user name of bot is "Bot", not Chinese...
It's just "我" instead of "me" after a private chat.I guess this is caused by a plug-in on the server.
It looks like it's right after testing the site.

![6613073f635a3ef8](https://user-images.githubusercontent.com/69417818/89997002-1c9a6980-dcbe-11ea-9083-a56d58286b42.jpg)

This is the message that bot received:

![3ebba933d3d1aa1b](https://user-images.githubusercontent.com/69417818/89998098-ac8ce300-dcbf-11ea-9408-4fab3d251367.jpg)

But the BOT still didn't respond😣

**Comment by ORelio** [comment] 2020-08-12 18:05
Indeed the username is not Chinese but by default MCC expects `me` not `我` so a regex is needed. Try setting `debugmessages=true` in config and debugging chat message detection with [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) it should show when a message is detected.

**Comment by ORelio** [comment] 2020-08-20 12:08
I'll close the issue as resolved. Feel free to reopen if you still need more info about regex.

**Closed by ORelio** 2020-08-20 12:08 UTC
Labels: a:question, in:chat-format-regex, resolved
