### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#192] opened 2016-08-28 23:46 UTC
basically this happens: http://prntscr.com/cbhvps
But it doesn't happen on every account. (I use multiple windows)
What do i do

**Comment by ORelio** [comment] 2016-08-29 07:36
Well, doesn't that seems like actual network errors causing disconnections?
Maybe you're connecting too many accounts to the same server at the same time?

**Comment by ORelio** [comment] 2017-03-13 21:42
Since this issue seems to be caused by network issues, and AutoRelog handles this case, I'll close the issue for now. Feel free to reopen if you feel something needs to be improved in MCC itself ;)

**Closed by ORelio** 2017-03-13 21:42 UTC
