### ISSUE TITLE
Question: Can we send commands trough an exe?

### ISSUE THREAD

**Issue by Ophornal** [ORelio/Minecraft-Console-Client#561] opened 2018-09-19 11:19 UTC
I was wondering if we could run command with a batch file
Like you can start your accounts with like start /min MinecraftClient.exe Mail Passw Server
But is there a way for it to automatically do /server survival and /home?
Thanks!

**Comment by TheSnoozer** [comment] 2018-09-19 22:04
yes.

> Try adding a `ScriptScheduler` or `AutoRespond`
> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

**Comment by Ophornal** [comment] 2018-09-29 10:31
Thank you so much!

**Comment by ORelio** [comment] 2018-11-15 19:43
As the issue is resolved I'm closing the thread. Feel free to reopen if needed.

**Closed by ORelio** 2018-11-15 19:43 UTC
