### ISSUE TITLE
Android Version?

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1338] opened 2020-11-15 21:18 UTC
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
It would be nice to have an Android version at least for the moment with basic chat functionality

**Comment by Mhowser** [comment] 2020-11-15 21:32
You could theoretically use Termux with mono on android, though I tried
before and had no success.

**Comment by ORelio** [comment] 2020-11-21 13:47
Closing as duplicate of #1000

**Closed by ORelio** 2020-11-21 13:47 UTC
Labels: a:enhancement, a:new-feature

**Comment by XIAYM-gh** [comment] 2021-02-03 06:06
It's easy to run on Android devices.
You need "AnLiunx" and "Termux", start Termux and install "debian" and "xfce4 desktop" from AnLiunx,
when you finish it, run command:
./star*
apt update
apt install mono-devel
After that, download (wget) MinecraftClient.exe from some way (such as FTP server on smartphones)
and run this command:
mono MinecraftClient.exe

Have fun ;)

**Comment by ORelio** [comment] 2021-02-03 17:58
@XIAYM-gh Looks cool! MCC being a console application, are you sure you need a desktop environment?

**Comment by XIAYM-gh** [comment] 2021-02-04 02:23
Hum, it's not necessary to install desktop, 
but I'm using VNC server to control it,
if you use it, you can run command quickly by keyboard...
Also, you can don't install it.

**Comment by ORelio** [comment] 2021-02-04 18:57
Oh, I see. So you're recycling an old Android phone to run MCC and remotely access it with VNC? I like the idea 😄
