### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by CleverMods** [ORelio/Minecraft-Console-Client#811] opened 2019-09-23 04:48 UTC
It signs in perfectly but after I load into the server, this pops up and the console client crashes

Error Code:

Unhandled Exception: System.IO.InvalidDataException: Failed to process incoming packet of type PlayerPositionAndLook. (PacketID: 53, Protocol: 498, LoginPhase: False, InnerException: System.OverflowException). ---> System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextVarInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, List`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TheSnoozer** [comment] 2019-09-23 07:27
Hello,
unfortunately I don't know yet where this issue is coming from and we have several similar issues with looks like the same root cause (https://github.com/ORelio/Minecraft-Console-Client/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+VarInt+too+big).

Could you perhaps
* share the server IP
* share your MinecraftClient.ini without any credentials and any needed files like tasks.ini or whatever is enabled?
* does this problem only appear on windows 10, mac or linux?

**Comment by CleverMods** [comment] 2019-09-24 00:07
54.39.141.147:25568
MinecraftClient.ini : https://hitler.cool/bPi.ini
On Windows 10

**Comment by marooyaho** [comment] 2019-09-28 06:24
I also have been having this same issue the past few days. I'm using an Ubuntu 16 VPS to host alts. I could easily run 10 at a time before, but now it only 2-4 will work. 

[MinecraftClient.txt](https://github.com/ORelio/Minecraft-Console-Client/files/3665146/MinecraftClient.txt)

The server I'm using is play.manacube.com, and using the anti-afk to connect to a subserver. I converted the config file to a .txt just so I could upload it into the reply. 

Just adding my file in case more data helps figure out what the issue is.

**Comment by TheSnoozer** [comment] 2019-09-28 08:47
Thanks @marooyaho! I'm trying to find the root cause of this issue for quite some time, but so far was unable to do so.

Some questions:
- do you have `msbuild` installed on the VPS where the alts are running?
- What subserver are you joining?
- Does this exception happen right after login, or just pops up randomly after some time?

**Comment by TNTUP** [comment] 2019-09-30 00:42
Confirming this issue, happens on my server at random areas

https://i.qcfb.ca/20190929204239.png

**Comment by ORelio** [comment] 2019-10-02 06:10
Since there is only one VarInt, it seems like the Teleport ID sent by the server is invalid (see [Player position and look](https://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29)), which is weird and not supposed to happen 🤔

**Comment by TheSnoozer** [comment] 2019-10-02 20:45
Do you think it would help if the client somewhat would print the raw data it tried to convert into a VarInt? At least I would like too see the data that causes this...I could not reproduce the issue so far (e.g. by joining play.manacube.com)

**Comment by ORelio** [comment] 2019-10-02 21:26
It might be useful to debug and/or print the data to see what the packet contains. Maybe a bug in the VarInt parser although unlikely: it is there since MC 1.7. Also, a possible hack could be to send back the remaining bytes of the packets (which should only contain the faulty varint provided by the server) and see what happens.

**Comment by TNTUP** [comment] 2019-10-02 21:49
> Do you think it would help if the client somewhat would print the raw data it tried to convert into a VarInt? At least I would like too see the data that causes this...I could not reproduce the issue so far (e.g. by joining play.manacube.com)

It happens at some places on my server, atleast one which I tested yesterday, you can try connecting to qcfb.ca then type /warp mcc. Let me know if it happens

**Comment by TheSnoozer** [comment] 2019-10-11 18:11
Anyone who has this problem:
could you perhaps download the latest build (https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and post the exception if any?

**Comment by TNTUP** [comment] 2019-10-14 00:48
@TheSnoozer There is! https://i.qcfb.ca/20191013204745.png

Exception non gérée : System.IO.InvalidDataException: Failed to process incoming packet of type PlayerPositionAndLook. (PacketID: 53, Protocol: 498, LoginPhase: False, InnerException: System.OverflowException). ---> System.OverflowException: VarInt too big C0-A1-8E-E7-F2-AD-3B-E1-40-51-40-00-00-00-00-00-C0-CD-C0-4D-20-C7-3E-9F-43-74-7F-B7-41-9D-FC-2B-00-01
   à MinecraftClient.Protocol.Handlers.DataTypes.ReadNextVarInt(List`1 cache)
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, List`1 packetData)
   --- Fin de la trace de la pile d'exception interne ---
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, List`1 packetData)
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by TheSnoozer** [comment] 2019-10-14 19:21
Interesting. It seems for me that the server is sending a full `PlayerPositionAndLook`-packet. At least when I construct the data you provided and mimic all the calls that would happen if `terrain` is enabled the processing seems to work fine:
```
case PacketIncomingType.PlayerPositionAndLook:
                        List<byte> fakeByteList = new List<byte>();
                        fakeByteList.Add(0xC0);
                        fakeByteList.Add(0xA1);
                        fakeByteList.Add(0x8E);
                        fakeByteList.Add(0xE7);
                        fakeByteList.Add(0xF2);
                        fakeByteList.Add(0xAD);
                        fakeByteList.Add(0x3B);
                        fakeByteList.Add(0xE1);
                        fakeByteList.Add(0x40);
                        fakeByteList.Add(0x51);
                        fakeByteList.Add(0x40);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0xC0);
                        fakeByteList.Add(0xCD);
                        fakeByteList.Add(0xC0);
                        fakeByteList.Add(0x4D);
                        fakeByteList.Add(0x20);
                        fakeByteList.Add(0xC7);
                        fakeByteList.Add(0x3E);
                        fakeByteList.Add(0x9F);
                        fakeByteList.Add(0x43);
                        fakeByteList.Add(0x74);
                        fakeByteList.Add(0x7F);
                        fakeByteList.Add(0xB7);
                        fakeByteList.Add(0x41);
                        fakeByteList.Add(0x9D);
                        fakeByteList.Add(0xFC);
                        fakeByteList.Add(0x2B);
                        fakeByteList.Add(0x00);
                        fakeByteList.Add(0x01);

                        double x = dataTypes.ReadNextDouble(fakeByteList);
                        double y = dataTypes.ReadNextDouble(fakeByteList);
                        double z = dataTypes.ReadNextDouble(fakeByteList);
                        float yaw = dataTypes.ReadNextFloat(fakeByteList);
                        float pitch = dataTypes.ReadNextFloat(fakeByteList);
                        byte locMask = dataTypes.ReadNextByte(fakeByteList);
                        int teleportID = dataTypes.ReadNextVarInt(fakeByteList);

                        throw new Exception(
                            "\n" +
                            "x=" + x +
                            ",y=" + y +
                            ",z=" + z +
                            ",yaw=" + yaw +
                            ",pitch=" + pitch +
                            ",locMask=" + locMask +
                            ",teleportID=" + teleportID +
                            ",remaining=" + fakeByteList.Count
                        );
```
Note that i purposefully throw an exception to see what is going on....anyhow it results in something that looks reasonable for me:
```
System.IO.InvalidDataException: Failed to process incoming packet of type PlayerPositionAndLook. (PacketID: 53, Protocol: 498, LoginPhase: False, InnerException: System.Exception). ---> System.Exception: 
x=-2247.45302335125,y=69,z=-15232.6025628143,yaw=244.4989,pitch=19.74813,locMask=0,teleportID=1,remaining=0
```
Remaining part seems to find out why this is happening.

Perhaps the most reasonable thing to have this patched is to go also into "processing a full packet" if we have more than 5 bytes. In specific change this
https://github.com/ORelio/Minecraft-Console-Client/blob/0529eb5162e08dfa528401fd529763b95c199fc6/MinecraftClient/Protocol/Handlers/Protocol18.cs#L229

to `if (handler.GetTerrainEnabled() || packetData.Count > 5)`.

The 5 here comes from the magic restriction that VarInts are never longer than 5 bytes.
@ORelio what do you think?

**Comment by Pokechu22** [comment] 2019-10-14 19:27
Is it failing on these lines:

https://github.com/ORelio/Minecraft-Console-Client/blob/0529eb5162e08dfa528401fd529763b95c199fc6/MinecraftClient/Protocol/Handlers/Protocol18.cs#L249-L254

?

Shouldn't those lines also be within the `handler.GetTerrainEnabled()` check?  Or, actually, it looks like they always need to run, but if `handler.GetTerrainEnabled()` is false, doesn't that mean that it won't have read the preceding data and thus it's not actually reading the VarInt?

**Comment by TheSnoozer** [comment] 2019-10-14 19:47
Yeah that was my first guess on this issue too. In https://github.com/ORelio/Minecraft-Console-Client/pull/758 I essentially changed this reading of the teleportID whenever Terrain is Enabled. Not sure, but based on the Feedback from ORelio that seemed to be have the wrong thing to do (honestly I don't know all details of the client, for me the you can configure the [`Terrain Enabled` via the settings](https://github.com/ORelio/Minecraft-Console-Client/blob/0529eb5162e08dfa528401fd529763b95c199fc6/MinecraftClient/McTcpClient.cs#L113) - I currently have `terrainandmovements=false` and saw incomming `PlayerPositionAndLook`-packets, however I could not reproduce the issue with multiple servers where it was reported)

**Comment by ORelio** [comment] 2019-10-29 18:55
Thanks @Pokechu22 I think this is the cause of the issue. Indeed, the teleport confirm need to be sent regardless of terrain enabled or not. Merged your PR!

**Closed** 2019-12-14 15:18 UTC
Labels: a:bug, resolved
