### ISSUE TITLE
Crash when using InteractEntity(entity.ID, 0, 0);

### ISSUE THREAD

**Issue by mexiscool** [ORelio/Minecraft-Console-Client#1304] opened 2020-11-01 16:11 UTC
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
A bug report should contain the following items:
* A clear and concise description of what the bug is
* Steps to reproduce the behavior
* What I expected to happen instead
* If applicable, add screenshots to help explain your problem
* Specify which kind of operating system you are running

**Description**
Crash when using InteractEntity(entity.ID, 0, 0); in script.

-add ''BotLoad(new AutoTrade());'' in McClient.cs at line 199
- save this code in AutoTrade.cs in ChatBots folder
```
using MinecraftClient.Inventory;
using MinecraftClient.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

//MCCScript 1.0
//MCC.LoadBot(new AutoTrade());
//MCCScript Extensions

namespace MinecraftClient
{
    public class AutoTrade : ChatBot
    {
        private bool sent = false;
        public override void OnEntityMove(Entity entity)
        {
            if (entity.Type == EntityType.Villager)
            {
                if (!sent)
                {
                    LogToConsole("1");
                    //InteractEntity(entity.ID, 2, 0, 0.3F, 1.4F, -0.01F);   (actually what the client sends before a normal interact but not supported yet)
                    InteractEntity(entity.ID, 0, 0);
                    LogToConsole("2");
                    SendAnimation(Inventory.Hand.MainHand);
                    //InteractEntity(entity.ID, 1); (attacking works so it's selecting the correct entity?)
                    LogToConsole("3");
                    sent = true;
                }

            }
        }
    }
}
```
- compile and enable entity handling and maybe also inventory handling.
- place bot/player next to a villager with a workstation and wait a second for the villager to move.

I expect to happen that the villager inventory is opened and the server sends back some packets.
console:
![image](https://user-images.githubusercontent.com/27775925/97807650-4e3e2380-1c62-11eb-90ca-6e0f2c50e0ab.png)
not that much to see sadly
server console:
![image](https://user-images.githubusercontent.com/27775925/97807685-7cbbfe80-1c62-11eb-927c-215866cf6950.png)

Running windows 10 tried it from within visual studio 2019 and with building it as described in Readme.
My best guess is that the packet sent to the server isn't correctly formatted. 

(also there is the option to use InteractEnitity with a 2 for interact at but in McClient.cs and ChatBot.cs there is no option to pass the x y z for that while there is a handler for it in IMinecraftCom.cs. When a real client interacts with a villager it sends the interact at and directly after that a normal interact (implementing this does not fix the crash tho))

**Comment by ReinforceZwei** [comment] 2020-11-01 16:15
Which Minecraft version are you using?

**Comment by mexiscool** [comment] 2020-11-01 16:15
1.16.3 but also tried it in 1.16.1

**Comment by ReinforceZwei** [comment] 2020-11-01 16:25
I will have a look at the issue when I have time.

**Comment by mexiscool** [comment] 2020-11-01 16:25
Ty

**Comment by ReinforceZwei** [comment] 2020-11-02 14:14
A careless mistake was made while upgrading to 1.16+. This issue will be fixed soon and your script should work as intended.

**Comment by mexiscool** [comment] 2020-11-02 15:38
Thanks again can confirm that it works

**Closed** 2020-11-02 18:01 UTC
Labels: a:bug, in:entity-handling
