### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by Forssmark** [ORelio/Minecraft-Console-Client#954] opened 2020-04-20 15:58 UTC
My console client isn't working i have tried multiple solutions this comes up 
and I have an idea to fix this problem cant you have the bot relog into the server instead of logging in to the account again or I think that is why I keep coming up would need some help with this thx

![image](https://user-images.githubusercontent.com/64026576/79772587-89b17a00-8330-11ea-8947-7bd96d4defb3.png)

![image](https://user-images.githubusercontent.com/64026576/79772454-638bda00-8330-11ea-834b-230e81092181.png)

**Comment by ORelio** [comment] 2020-04-20 17:09
You are not using the latest build, your issue was fixed in commit 52248d1abaf9b03047f90caa465f5f0b466f7c56. Duplicate of #951.

**Closed by ORelio** 2020-04-20 17:09 UTC
