### ISSUE TITLE
Login failed: Failed to check session

### ISSUE THREAD

**Issue by lackofcreativename** [ORelio/Minecraft-Console-Client#969] opened 2020-04-23 16:23 UTC
debug output:

Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 - By ORelio & Contributors
Resolving play.manacube.net...
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTdmZDJiOTFhM2M0ZjgyYjQwNTcxY2NiYWE5YWI1ZiIsInlnZ3QiOiI0YjZkMmVhMjcxYTg0M2NmYTZhZWZhMzYyZjBkZDQ4NCIsInNwciI6IjExZmFmNzAzMzRjODQ3YzRiNTc0NjUwYTcwOGIyYWJlIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc4MzE2NDMsImlhdCI6MTU4NzY1ODg0M30.sijGu4uMiL5AU_x3d8f2bqTwej-1uedzxvZ9KXeJFyk,Kevin_K11,11faf70334c847c4b574650a708b2abe,d4ef9d634b3948c2912e5ef8286ae155': Invalid session ID
No sessions could be loaded from disk
Login : natureboyricflair@web.de
Password : <******>                                                                                                     Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.12.2
> Content-Type: application/json
> Content-Length: 182
> Connection: close
>
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "<username>", "password": "<password>", "clientToken": "eeb32a655c5249659e4bb82525ff3faa" }

< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 537
< Connection: close
< Accept-Ranges: bytes
< Date: Thu, 23 Apr 2020 16:21:41 GMT
< Server: Restlet-Framework/2.4.1
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
< X-Cache: Miss from cloudfront
< Via: 1.1 f87d710cc60916d8144c2435a76eb7d6.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: YTO50-C1
< X-Amz-Cf-Id: UKghBIx4VMKZw4Rt6MoJfVHBLPvPn7FOLK7hQ0ky5xOMqHCITvIvJg==
<
< {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTdmZDJiOTFhM2M0ZjgyYjQwNTcxY2NiYWE5YWI1ZiIsInlnZ3QiOiIzYzc0NmIwOWY5ZTM0ZGMzOWZhYTI3MzdjYjIyZGQyYyIsInNwciI6IjExZmFmNzAzMzRjODQ3YzRiNTc0NjUwYTcwOGIyYWJlIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc4MzE3MDEsImlhdCI6MTU4NzY1ODkwMX0.B0GV6lfkbcgursuT8Env8JZN98KCsb9MmQ_kbIsB4f0","clientToken":"eeb32a655c5249659e4bb82525ff3faa","selectedProfile":{"name":"Kevin_K11","id":"11faf70334c847c4b574650a708b2abe"},"availableProfiles":[{"name":"Kevin_K11","id":"11faf70334c847c4b574650a708b2abe"}]}
Saving session cache to disk
Success. (session ID: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTdmZDJiOTFhM2M0ZjgyYjQwNTcxY2NiYWE5YWI1ZiIsInlnZ3QiOiIzYzc0NmIwOWY5ZTM0ZGMzOWZhYTI3MzdjYjIyZGQyYyIsInNwciI6IjExZmFmNzAzMzRjODQ3YzRiNTc0NjUwYTcwOGIyYWJlIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc4MzE3MDEsImlhdCI6MTU4NzY1ODkwMX0.B0GV6lfkbcgursuT8Env8JZN98KCsb9MmQ_kbIsB4f0)
Server IP : Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTdmZDJiOTFhM2M0ZjgyYjQwNTcxY2NiYWE5YWI1ZiIsInlnZ3QiOiIzYzc0NmIwOWY5ZTM0ZGMzOWZhYTI3MzdjYjIyZGQyYyIsInNwciI6IjExZmFmNzAzMzRjODQ3YzRiNTc0NjUwYTcwOGIyYWJlIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc4MzE3MDEsImlhdCI6MTU4NzY1ODkwMX0.B0GV6lfkbcgursuT8Env8JZN98KCsb9MmQ_kbIsB4f0,Kevin_K11,11faf70334c847c4b574650a708b2abe,eeb32a655c5249659e4bb82525ff3faa': Invalid session ID
play.manacube.net
Resolving play.manacube.net...
Using Minecraft version 1.8.9 (protocol v47)
[MCC] [ScriptScheduler] File not found: 'tasks.ini'
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.12.2
> Content-Type: application/json
> Content-Length: 433
> Connection: close
>
> {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTdmZDJiOTFhM2M0ZjgyYjQwNTcxY2NiYWE5YWI1ZiIsInlnZ3QiOiIzYzc0NmIwOWY5ZTM0ZGMzOWZhYTI3MzdjYjIyZGQyYyIsInNwciI6IjExZmFmNzAzMzRjODQ3YzRiNTc0NjUwYTcwOGIyYWJlIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc4MzE3MDEsImlhdCI6MTU4NzY1ODkwMX0.B0GV6lfkbcgursuT8Env8JZN98KCsb9MmQ_kbIsB4f0","selectedProfile":"11faf70334c847c4b574650a708b2abe","serverId":"7f944ba02b2605a4f71da9219c30fd8d7047d161"}

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Connection: close
< Date: Thu, 23 Apr 2020 16:21:46 GMT
< x-minecraft-request-id: 6d5f7d8a72518818
< X-Cache: Miss from cloudfront
< Via: 1.1 a65e8802f41d2805ddc8578873f004a2.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: YTO50-C2
< X-Amz-Cf-Id: utgXjTq3Iloi7ZCCBWJ8z6vicPZyy4dt3e1pt348QSRUobh5MjSdLQ==
<
< 0
<
<
**Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.**
>

**Comment by TaranArora** [comment] 2020-04-23 23:20
Have you downloaded the latest development build?if not do so and see if the problem goes away.

**Comment by slutfarm** [comment] 2020-04-24 08:46
Issue is present in the new development build.

**Comment by ORelio** [comment] 2020-04-24 10:39
You are not using the latest build, your issue was fixed in commit 52248d1abaf9b03047f90caa465f5f0b466f7c56. Duplicate of #951.

**Closed** 2020-04-24 10:39 UTC
Labels: a:bug, in:connect-to-server, rejected:duplicate
