### ISSUE TITLE
Crashs :/

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#173] opened 2016-07-05 22:55 UTC
There's unknown crash(es) while teleporting to the end world /w e (http://i.qcfb.ca/20160705185324.png) and if the height is far more than 256, the client crash (http://i.qcfb.ca/20160705184953.png) I guess those ones are the same, but the /w e isn't 256, quite at 57. I guess they can can crash below 57? :x: 

EDIT: Another crash, while walking into the void makes the client crash. I guess those crashes are related due they spawn in the air instead on the floor

**Comment by ORelio** [comment] 2016-07-18 08:52
Okay, the second one seems easy to fix, that's because of trying to access a chunk section above 256 (or below 0 regarding crash in your EDIT line). Regarding the first one I think I'll need line numbers in the stack trace, or reproduce it on my side. Server version is 1.9.4(?)
Thanks for your reports! (Sorry for the late reply)

**Comment by TNTUP** [comment] 2016-07-18 18:09
The first one I guess it's related due the warp is in the "void" while typing /w e (the warp height I guess.. by example 60, but the floor where the warp is located is 55)

**Comment by ORelio** [comment] 2016-07-22 20:18
Okay, so, index out of range for > 256 and < 0 fixed but ProcessChunkColumnData() is a bit large so does it always happen 100% of time in your server when using a particular warp? I guess it whould help me figure it out if I gould try it out on your server myself.

**Comment by TNTUP** [comment] 2016-07-22 20:22
Well must be the end world doing this, I've teleported another console client in the end world and he crashed. Wasn't in the air while I've tp'd him there (probably due to 1.9.4-1.10 compat (Viaversion)? I guess we can close this issue now :)

**Comment by ORelio** [comment] 2016-07-22 21:49
Indeed, The End didn't load at all. Should be fixed now. Thanks for your report :)

**Closed by ORelio** 2016-07-22 21:49 UTC
