### ISSUE TITLE
Need Right Click to Npc

### ISSUE THREAD

**Issue by Meka4756** [ORelio/Minecraft-Console-Client#798] opened 2019-09-01 10:08 UTC
Hello. Needed right click to a NPC (creative , minigames , survival..) to connect some servers. I didnt found a way to right clicking.

**Comment by AggroMC** [comment] 2019-12-25 19:21
Mei pech host hoid khod, mia kinans a ned ändern.

**Comment by Meka4756** [comment] 2019-12-26 09:34
> Mei pech host hoid khod, mia kinans a ned ändern.

Can you write in English?

**Comment by ORelio** [comment] 2020-02-13 20:42
This is currently not implemented. Closing as duplicate of #183

**Closed by ORelio** 2020-02-13 20:42 UTC
