### ISSUE TITLE
OverflowException: VarInt too big

### ISSUE THREAD

**Issue by irfatftw** [ORelio/Minecraft-Console-Client#458] opened 2018-05-25 00:19 UTC
Getting the following error when trying to connect to a server with only one account.  Connects to the hub fine but crashes when choosing a server to go to:
https://gyazo.com/7fb37abd3a56409152d202e4bd371255

**Comment by meciless** [comment] 2018-05-25 07:51
I got the same problem first time i login and read other issues my problem solved.
Solution:
MinecraftClient.ini
# Advanced settings
(terrainandmovements=true ) instead of terrainandmovements=false.

**Comment by ORelio** [comment] 2018-05-25 16:57
There was a report for this in #432 but I was not able to reproduce. Would you mind giving the server IP so that I could try it out and see what's wrong when terrain and movement is disabled?

**Comment by TheSnoozer** [comment] 2018-11-19 22:46
Closing as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379

**Closed by TheSnoozer** 2018-11-19 22:46 UTC
Labels: a:bug, in:connect-to-server
