### ISSUE TITLE
Passwords with ! or ] do not get authenticated. 

### ISSUE THREAD

**Issue by JamieSinn** [ORelio/Minecraft-Console-Client#47] opened 2014-10-09 01:58 UTC
You cannot enter a password with ! or ] in it, in any form
You must use the ini file to log in.
Gives you a bad password error otherwise.

**Comment by JamieSinn** [comment] 2015-05-18 17:01
You can use an escape character "\" to make it work, eg. \] \!

**Comment by ORelio** [comment] 2015-06-19 18:24
After digging a bit - better late than never! - I can properly authenticate with ! or ] chars in my password, by typing it in the MCC console prompt, as usual. Funny thing, I was not able to log back to Minecraft.net with such a weird password - but in MCC I can - and had to reset it by email. Anyway, I can't reproduce your issue.

**Comment by JamieSinn** [comment] 2015-07-14 05:10
Can you log in with a password that has  !] beside eachother, I still cannot

**Comment by ORelio** [comment] 2015-07-17 21:03
The ] key on QWERTY keyboard was indeed ignored while typing passwords, my bad.
My own keymap isn't QWERTY that's why I didn't notice the issue.
Please confirm using [dev builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/) that the issue is fixed for you :)

**Comment by Pokechu22** [comment] 2015-08-19 02:25
Confirmed fixed as of ebc4d9f, using password `test[123!456`.

**Closed** 2015-08-19 02:56 UTC
