### ISSUE TITLE
Client crashes w/ terrain movement

### ISSUE THREAD

**Issue by ghost** [ORelio/Minecraft-Console-Client#217] opened 2016-11-09 17:18 UTC
https://upload.thomasisa.ninja/MinecraftClient_2016-11-09_17-15-57.png

Client config: 
https://upload.thomasisa.ninja/2016-11-09_17-17-44.txt

No idea what version I'm using. Whatever I found on MCForum 7th November. The client crashes ~5secs after joining.

**Comment by ORelio** [comment] 2016-11-09 17:39
Please double check you are using the latest développent build (please see link on top of forum post) and provide full ouput. Thanks!

**Comment by Chearful** [comment] 2016-11-14 22:24
Using the latest dev build, still same error.

**Comment by ORelio** [comment] 2016-11-15 07:45
Okay, how is the server detected? What version? Your screenshot does not display lines before "Logging in" and details about server version are useful for trying to reproduce.

**Comment by Chearful** [comment] 2016-11-16 08:06
`Version
1.7.x, 1.8.x, 1.9.x, 1.10.x
Software
Cosmos`

AFAIK the issue got fixed in the dev build from P/R #218 .

**Comment by ORelio** [comment] 2016-11-16 09:39
Well, that wasn't supposed to fix anything on your side, but at least it's solved :sweat_smile:

**Comment by Chearful** [comment] 2016-11-16 17:31
Argh, got to re-open it as it's crashed again ;(

http://i.imgur.com/3Lau0Ts.png

**Comment by ORelio** [comment] 2016-11-18 07:08
OK, seems like there is an issue with block light or sky light while processing terrain received from the server, which dimension are you in? Is that server running Minecraft 1.9 or greater?

**Comment by Chearful** [comment] 2016-11-18 14:59
It's in the end, the server is 1.7 afaik or 1.8, but supports from 1.7 -> 1.10.

**Comment by ORelio** [comment] 2016-11-18 15:53
Can you craft armor stands and banners?

  - No -> 1.7
  - Yes : Can you craft shields?
 - Yes -> 1.9+
 - No -> 1.8

**Comment by Pokechu22** [comment] 2016-11-18 15:57
If it supports multiple versions down to 1.7, the server needs to run 1.7 (the major multi-version plugin only lets you access from newer versions).  

That said: not only 1.9 skip skylight data.  In 1.8 and 1.7, skylight _also_ is not sent in the nether and the end.

Looks like MCC doesn't follow that for 1.8 though, instead using just a constant `hasSkylightData`.  That causes issues in the nether and end.

**Comment by ORelio** [comment] 2016-11-19 15:25
1.7 chunk data handling has been added very late and wasn't that much tested.
Just pushed a fix applying @Pokechu22's suggestion, please try it out.

**Comment by PhotonicMatter** [comment] 2016-12-06 20:56
Happens on a 1.8 server... once I enable TerrainAndMovements

Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Using Minecraft version 1.8.0 (protocol v47)
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
>
Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, List`1 cache)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment] 2016-12-07 10:07
Please retry with the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) to see if it's fixed or not :)

**Comment by ORelio** [comment] 2017-03-13 21:17
As there are no feedback I'll assume the issue is now resolved. Feel free to reopen if that's not the case.

**Closed by ORelio** 2017-03-13 21:17 UTC
