### ISSUE TITLE
Moving through Portal won't work

### ISSUE THREAD

**Issue by NateDaBeast** [ORelio/Minecraft-Console-Client#671] opened 2019-03-15 22:28 UTC
I've run into an issue where because you join a hub first, I can't get into the factions server.

I've tried the /server command but they must have it on some secret name.

I've tried the /move command but even tho that the portal is south and you spawn in facing south, and I try /move south it never goes through the portal and ends up saying like "you cant move anymore" or something like that. I've tried coordinates too but don't know how to enter them apparently.

So could someone teach me how to use the /move command correctly? Or better, figure out the name of for the /server command if that's even possible.

Thanks!

**Comment by NateDaBeast** [comment] 2019-03-15 22:36
This is what it says by the way when I try using the command:
>/move
MCC: move <get|up|down|east|west|north|south|x y z>: walk or start walking.
>/move 1 127 0
MCC: Failed to compute path to X:1 Y:127 Z:0

**Comment by NateDaBeast** [comment] 2019-03-15 22:52
So I manually did /move via directions, and the issue I've run into now is that because the portal is water it won't walk into it. Any way to fix??

**Comment by TheSnoozer** [comment] 2019-03-17 01:56
Might be related to https://github.com/ORelio/Minecraft-Console-Client/issues/553

**Comment by TheSnoozer** [comment] 2019-03-17 01:57
Just curious....can you join a server without walking through a portal? like `/server XYZ``whereby the XYZ gets replaced with the realm name?

**Comment by ORelio** [comment] 2019-04-18 05:19
A portal block is considered as non-solid by MCC, as such you can walk into it.
Just checked on a local, vanilla server, it works:

/move east
![2019-04-18_08 11 32](https://user-images.githubusercontent.com/1128206/56338247-95141780-61a9-11e9-9455-5a6edffc0d48.png)
Then, after a few seconds:
![2019-04-18_08 11 35](https://user-images.githubusercontent.com/1128206/56338250-96dddb00-61a9-11e9-8b08-e9876cec2782.png)
With additional /move commands, the bot takes the portal back from the Nether:
![2019-04-18_08 15 45](https://user-images.githubusercontent.com/1128206/56338324-e3c1b180-61a9-11e9-985f-a0c7e2e670f5.png)

Make sure your bot is moving properly ingame, and no plugin is interferring with its movements. If you need to climb to the portal, move to the correct location and take note of XYZ coordinates in F3, then put them in /move X Y Z syntax. Also just in case, make sure you are using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by TheSnoozer** [comment] 2019-09-20 19:27
For now it seems that the movement is working (perhaps the issue was fixed?) and thus I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if the issue is still present with the latest version.

As suggested before you try again download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client).

**Closed by TheSnoozer** 2019-09-20 19:27 UTC
Labels: a:question, in:terrain-handling
