### ISSUE TITLE
Implement Click/Right Click

### ISSUE THREAD

**Issue by Joehainess** [ORelio/Minecraft-Console-Client#570] opened 2018-10-09 17:26 UTC
Is there a way to get a console client to click, and if so how?
If there isnt a way, is it going to soon, and when can we expect to see that if so?

**Comment by TheSnoozer** [comment] 2018-10-10 10:17
Short:
Yes possible, but very unlikely that this will ever get implemented within this console client.

Long:
Technically it is possible to have console clients to perform a "Click/Right Click" however as far as I know the specific packets needed are currently not implemented.
Unfortunately as far as I understand it the owner of the project moved on with different projects and thus will not likely have time to work on those. Unless someone else will implement them it is very unlikely that those will ever become available within this client.

**Comment by ORelio** [comment] 2018-11-07 21:58
Hi, @TheSnoozer is correct. I do not have enough time to add new features or new Minecraft versions, however if someone with C# knowledge is willing to work on the project, I can provide general guidance on how MCC and the [Minecraft protocol](https://wiki.vg/) works. Any contribution is welcome.

**Comment by ORelio** [comment] 2018-11-15 19:55
Closing as duplicate of #171

**Closed by ORelio** 2018-11-15 19:55 UTC
