### ISSUE TITLE
The player not Knockback

### ISSUE THREAD

**Issue by iwixw** [ORelio/Minecraft-Console-Client#1655] opened 2021-06-28 08:35 UTC
The player does not lean back when hitting another player

**Comment by ReinforceZwei** [comment] 2021-06-28 09:15
Player knock back is not handled. Converting your bug report to enhancement.

**Comment by ORelio** [comment] 2021-06-30 15:48
As strange as it sounds, knockback is not done server-side but client-side and MCC simply does not implement it.
I'll close this as duplicate of #356

**Closed by ORelio** 2021-06-30 15:48 UTC
Labels: a:enhancement, in:entity-handling, in:terrain-handling, waiting-for:contributor
