### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by MattoBois** [ORelio/Minecraft-Console-Client#387] opened 2018-02-11 11:11 UTC
So I can join the server mc.good-gaming.com but i cannot warp to any of the game modes because it would give me a bunch of text and crash me. 
![image](https://user-images.githubusercontent.com/36364858/36072720-49a21cbc-0f74-11e8-9ca3-31d6a64e52cd.png)

**Comment by ORelio** [comment] 2018-02-11 14:49
Seems related to #379, unfortunately the root cause for this has not been identified yet.

**Comment by TheSnoozer** [comment] 2018-11-19 22:44
I'm closing this, since it seems to be a duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379

**Closed by TheSnoozer** 2018-11-19 22:44 UTC
Labels: a:bug, in:connect-to-server
