### ISSUE TITLE
A way to drop items in inventory

### ISSUE THREAD

**Issue by coolboycosmo** [ORelio/Minecraft-Console-Client#337] opened 2017-10-17 21:56 UTC
It there a way to make the accounts in console client drop items?

**Comment by Pokechu22** [comment] 2017-10-17 22:18
Not at this time; see #205

**Comment by TheSnoozer** [comment] 2018-11-29 13:22
Thanks for opening an issue, I'm closing this as duplicate of #205, as part of an issue cleanup.

**Closed by TheSnoozer** 2018-11-29 13:22 UTC
Labels: rejected:duplicate
