### ISSUE TITLE
Client can't connect to 1.8 spigot Server

### ISSUE THREAD

**Issue by lyze237** [ORelio/Minecraft-Console-Client#67] opened 2015-03-02 16:28 UTC
pi@raspberrypi ~/mc $ mono MinecraftClient.exe MinecraftClient.ini
    Console Client for MC 1.4.6 to 1.8.1 - v1.8.0 - By ORelio & Contributors
    Connecting to Minecraft.net...
    Success. (session ID: [...])
    Using Minecraft version 1.8.0 (protocol v47)
    Failed to connect to this IP.
    [BOT] Waiting 5 seconds (3 attempts left)...
    Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object

Where the ip is correct and pingable.

    pi@raspberrypi ~/mc $ ping <ip>
    PING <ip> (<ip>) 56(84) bytes of data.
    64 bytes from <ip>: icmp_req=1 ttl=54 time=41.5 ms
    64 bytes from <ip>: icmp_req=2 ttl=54 time=38.4 ms
    64 bytes from <ip>: icmp_req=3 ttl=54 time=38.2 ms
    64 bytes from <ip>: icmp_req=4 ttl=54 time=46.9 ms

Where this is the config file:

    login=<username>
    password=<password>
    serverip=<ip>:4464

Perhapse it can't connect to Servers with a custom port number

Note i'm using the Spigot Version: CraftBukkit version git-Spigot-952179b-f98775c (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by ORelio** [comment] 2015-03-02 17:52
Hello,
Thanks for your report.
Please provide the stack trace (lines below NullReferenceException)  :)

**Comment by lyze237** [comment] 2015-03-02 17:54
Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object
      at MinecraftClient.McTcpClient.Disconnect () [0x00000] in <filename unknown>:0 
      at MinecraftClient.Program.<Restart>b__4 () [0x00000] in <filename unknown>:0 
      at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
    [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
      at MinecraftClient.McTcpClient.Disconnect () [0x00000] in <filename unknown>:0 
      at MinecraftClient.Program.<Restart>b__4 () [0x00000] in <filename unknown>:0 
      at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by ORelio** [comment] 2015-03-02 20:46
Thanks for your report, the crash has been fixed!

Regarding the issue with this particular server: Even if ping is working this does not means that a Minecraft server is running on the server on port 25565. Or 4464 in your case. The app actually properly handles the ip:port syntax so I dont't know why it can't even etablish a connection.

As you are running the app on a raspberry pi I guess you haven't tried on the Minecraft game itself, but could you try connecting on a computer where you are sure you can connect to the server?

**Comment by lyze237** [comment] 2015-03-02 21:01
No the Server is online and i'm connected to it.

**Comment by ORelio** [comment] 2015-03-02 21:11
I mean, can you try connecting using Minecraft Console Client, on a computer where you can access the server using the main Minecraft Game.

**Comment by lyze237** [comment] 2015-03-02 21:13
i have also tried it. arch linux + mono from repo. same error

**Comment by ORelio** [comment] 2015-03-02 21:16
I think the issue is on a lower level because it means that when in my code i use the function to connect using TCP to "the given server", it fails whereas a server should be reachable: this is outside my code. For investigation purposes, could you provide the server IP and port? I suspect a DNS record issue while resolving "the sever address" (eg my.server.com) to "the server IP" (eg 123.123.123.123).

**Comment by lyze237** [comment] 2015-03-02 21:21
mc.lyze.at or zap.lyze.at:4464
i have tried both: both domain names and ip (only the numbers)

**Comment by ORelio** [comment] 2015-03-02 21:55
mc.lyze.at -> cannot resolve (get a SOA dns record, "Unknown Host" from Minecraft)
zap.lyze.at -> can resolve (get a A dns record, but "Connection Refused" from Minecraft)
Anyway the DNS records for zap.lyze.at seems normal. But I cannot connect with the Minecraft game.

**Comment by lyze237** [comment] 2015-03-02 22:23
Well thats weird.
I can normally connect to mc.lyze.at, zap.lyze.at:4464 and 134.255.231.125:4464

http://i.imgur.com/w7X1HhG.png | http://i.imgur.com/742FPKK.png
The pi is in the same network as the computer i took screenshots from.

**Comment by ORelio** [comment] 2015-03-02 23:36
Don't know why, but the addresses are now working except `mc.lyze.at`:

![2015-03-03_00 25 01](https://cloud.githubusercontent.com/assets/1128206/6453260/70d9c282-c13c-11e4-8553-16289a631f0a.png)

And when trying `zap.lyze.at:4464` the client can properly connect:

![reachable](https://cloud.githubusercontent.com/assets/1128206/6453326/1f776d08-c13d-11e4-9013-a0530bd8e5f6.png)

Not tried to actually login but it seems to work, no "Failed to connect" issue :confused:
I'm using the [current source code](https://github.com/ORelio/Minecraft-Console-Client/tree/e4916033fa2c4d46891bf5241e0eee792d89455b) from Indev branch but it should work the same way with MCC v1.8.0

**Comment by lyze237** [comment] 2015-03-03 16:06
Ok thanks. Currently connecting works with zap.lyze.at:4464.

It works normally when i start it myself via
    mono MinecraftClient.exe MinecraftClient.ini BasicIO.

However when i try to start it as a cronjob at every Systemreboot the Client connects and disconnects after a second or two.

Thats the cronjob entry:
     # m h  dom mon dow   commandß
    @reboot sudo mono /home/pi/mc/MinecraftClient.exe /home/pi/mc/MinecraftClient.ini BasicIO > /home/pi/mc/log.txt

Thats the log file:
    pi@raspberrypi ~ $ cat mc/log.txt
    Console Client for MC 1.4.6 to 1.8.1 - v1.8.0 - By ORelio & Contributors
    Connecting to Minecraft.net...
    Success. (session ID: <id>)
    �8Using Minecraft version 1.8.0 (protocol v47)
    �8[BOT] File not found: kickmessages.txt
    �8Translations file loaded.
    Version is supported.
    Logging in...
    �8Crypto keys & hash generated.
    Checking Session...
    Server was successfully joined.
    Type '/quit' to leave the server.
    �e�elyze237Test joined the game�r
    Welcome, lyze237Test! Ya can see the statistics at �rhttp://statistics.lyze.at/�r
    �6�6Welcome, �r�f�f[�r�2�2Bird�r�f�f] lyze_bot_1�r�6�6!�r
    �6�6Type �r�c�c/help�r�6�6 for a list of commands.�r
    �6�6Type �r�c�c/list�r�6�6 to see who else is online.�r
    �6�6Players online:�r�c�c 2 �r�6�6- World time:�r�c�c 12:20 PM�r
    �6�6You have no new mail.�r

**Comment by ORelio** [comment] 2015-03-04 10:52
Not sure why it does not work properly as a job, there is no particular reason why it would not work as a job but would work when manually launched. However, mono's implementation of AES crypto is incomplete so the current workaround to get the app working on mono will lose connection if no interaction is made (no message sent or received during a certain amount of time, ~30 secs). See thread post no [955](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1263927-win-mac-linux-minecraft-console-client-1-8-0?comment=955) for detailed info. The app will properly work with the regular .NET framework, which is [getting open source](https://github.com/Microsoft/dotnet) and should eventually be ported to linux in the future, resolving the issue.

**Closed** 2015-03-11 17:36 UTC
