### ISSUE TITLE
allow us to choose our own console colors

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#444] opened 2018-05-17 00:16 UTC
LogToConsole uses an invisible (same as background) color for me in my console

**Comment by TheSnoozer** [comment] 2019-09-20 15:54
I'm closing this as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/216, please follow the linked issue.

**Closed by TheSnoozer** 2019-09-20 15:54 UTC
