### ISSUE TITLE
Task.ini onlogin work just once

### ISSUE THREAD

**Issue by meciless** [ORelio/Minecraft-Console-Client#449] opened 2018-05-22 07:47 UTC
Offline mode use:
First time onlogin is working but if server disconnect and autorelog working onlogin does not work like the first time.

**Comment by ORelio** [comment] 2018-05-23 17:28
Well, that's the intended behavior, since you're logging in for the second time. You probably want to use `TriggerOnLogin` instead of `TriggerOnFirstLogin`?

**Comment by meciless** [comment] 2018-05-24 09:56
[Task]
triggerOnLogin=true
script=skyblock.txt

First, login script work but after autorecconect, script does not working.

**Comment by ORelio** [comment] 2018-05-24 17:14
OK so that is an issue, I'll look into this.

**Comment by Barnehhh** [comment] 2018-05-24 17:16
I can second this, runs the first time with triggerOnLogin but anytime after with reconnect there's nothing.

**Comment by meciless** [comment] 2018-06-05 07:28
How is the situation this problem? is it solved ?

**Comment by ORelio** [comment] 2018-06-06 06:33
Not enough time to handle all the issues. Contributions are welcome!

**Comment by drcheap** [comment] 2018-06-19 17:15
This is the same as #427

**Comment by madl-ash** [comment] 2018-06-23 07:11
+1

**Comment by TheSnoozer** [comment] 2019-09-23 21:21
This was most likely fixed by https://github.com/ORelio/Minecraft-Console-Client/pull/809 could you perhaps download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try again?

**Closed** 2019-12-14 15:13 UTC
Labels: a:bug, in:scripts-and-bots, resolved
