### ISSUE TITLE
Can't join 1.15.2 forge server

### ISSUE THREAD

**Issue by tomekb530** [ORelio/Minecraft-Console-Client#1184] opened 2020-08-07 14:10 UTC
Whenever i want to join 1.15.2 Forge server i am getting "This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
Failed to login to this server."

**Comment by ORelio** [comment] 2020-08-07 18:11
`mcversion=1.15.2`
`mcforge=auto`
And make sure you have a recent build.

**Comment by tomekb530** [comment] 2020-08-08 00:36
I added those, and still `Console Client for MC 1.4.6 to 1.16.1 - v1.16.1 - By ORelio & Contributors
AppVeyor build 360, built on Fri 08/07/2020 from commit ce83cc0
[MCC] [Settings] Loading Settings from C:\Users\tomek\Desktop\MinecraftClient.ini
You chose to run in offline mode.
Using Minecraft version 1.15.2 (protocol v578)
Checking if server is running Forge...
Server version : 1.15.2 (protocol v578).
Downloading 'en_GB.lang' from Mojang servers...
Done. File saved as 'lang\en_GB.lang'
Version is supported.
Logging in...
Login failed :
This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
Failed to login to this server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.`

**Comment by ORelio** [comment] 2020-08-08 10:48
Seems like your server does not report to be running Forge. As a result, MCC cannot retrieve the mod list reported by the server and pretend to have everything installed correctly in order to pass the login check performed by Forge server-side.

**Comment by Nekiplay** [comment] 2020-08-08 11:15
It would not be bad to add forcefoge=true to the settings

**Comment by ORelio** [comment] 2020-08-08 11:17
@Nekiplay This would be pointless. We need to perform the server ping to retrieve the mod list. Hence the `auto`.

**Comment by ORelio** [comment] 2020-08-08 12:31
Please retry with the latest build, and set `debugmessages=true`. I added server ping raw result to the debug messages, please post that to see if it contains anything about Forge running on your server.

**Comment by tomekb530** [comment] 2020-08-08 13:02
https://screen.tomekb530.me/tomek/VibrantKob5520 there is all log, the forge is present in the ping JSON

**Comment by tomekb530** [comment] 2020-08-08 13:03
and here is what iam getting in srv console https://screen.tomekb530.me/tomek/BusyMuskrat5868

**Comment by ORelio** [comment] 2020-08-08 17:52
Thanks, this is the interesting part
```json
{"description":{"text":"A Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.15.2","protocol":578},"forgeData":{"channels":[{"res":"minecraft:unregister","version":"FML2","required":true},{"res":"minecraft:register","version":"FML2","required":true},{"res":"citadel:main_channel","version":"1","required":false},{"res":"rats:main_channel","version":"1","required":false}],"mods":[{"modId":"minecraft","modmarker":"1.15.2"},{"modId":"forge","modmarker":"ANY"},{"modId":"rats","modmarker":"5.3.2"},{"modId":"citadel","modmarker":"1.1.11"}],"fmlNetworkVersion":2}}
```

**Comment by ORelio** [comment] 2020-08-08 19:23
Seems like the Forge handshake has changed in Minecraft 1.13: https://wiki.vg/Minecraft_Forge_Handshake
I'll implement the newer variant and let you check if it works.

**Comment by ORelio** [comment] 2020-08-08 20:10
Done. You can check how the newer build interacts with your server. Should at least retrieve the mod list and attempt to log in.

**Comment by tomekb530** [comment] 2020-08-08 23:36
It sits on Logging in... and nothing more

**Comment by ORelio** [comment] 2020-08-09 16:46
Do you have a copy of server jar with mods or server IP so that I can attempt to reproduce and see what's wrong?

**Comment by tomekb530** [comment] 2020-08-10 16:30
https://screen.tomekb530.me/tomek/mcok.zip here you are :)

**Comment by ORelio** [comment] 2020-08-10 20:43
Thanks. Seems like Forge is using a brand new protocol (FML2) so we need to reimplement all the Forge login procedure.
This will likely take a while although I'm starting to dig the [MinecraftForge](https://github.com/MinecraftForge/MinecraftForge) repository and already found some documentation 😉

**Comment by ORelio** [comment] 2020-08-11 11:28
Minecraft Console Client now supports Forge for Minecraft 1.13 and greater. Tested working with your Forge version 👍

**Comment by ORelio** [comment] 2020-08-13 19:12
@Pokechu22 Documented the FML2 protocol. It's much simpler than the previous version 😉
https://wiki.vg/Minecraft_Forge_Handshake#FML2_protocol_.281.13_-_Current.29

**Comment by ORelio** [comment] 2020-08-20 12:09
I'll close the issue as resolved. Feel free to reopen if you still cannot join your Forge server.

**Comment by Mysterius** [comment] 2020-10-04 18:43
Hello,

I have the same problem with the latest dev build and MC 1.15.2 with Forge 31.2.43.
Am I doing something wrong ? 

I'm trying this on a local LAN server (using _127.0.0.1:port_ to connect).

**Comment by ReinforceZwei** [comment] 2020-10-04 18:47
@Mysterius Could you enable debug message in configuration file and attach the full console output to here?

**Comment by Mysterius** [comment] 2020-10-04 18:50
I edited my previous message to paste it just while you were writing your answer, I think ;). Sorry !

**Comment by ORelio** [comment] 2020-10-05 19:51
This server lacks Forge information in its server ping response so MCC does not detect it.
However, unlike FML1, I think it is possible to force FML2 even if missing in ping response, we need a setting for this.
I'll reopen the issue.

**Comment by ORelio** [comment] 2020-10-18 11:13
@Mysterius In the latest development build, you can now set `mcforge=true` to completely skip the server info step and join with Forge support enabled. Of course, this only works for MC 1.13+ because we need the mod list from server info for successfully joining server with older Forge versions (1.12.X and lower).

**Closed** 2020-10-18 11:17 UTC
Labels: a:enhancement, in:connect-to-server, in:protocol-compatibility, resolved
