### ISSUE TITLE
Sometimes it stuck with "Logging in..."

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1321] opened 2020-11-09 14:47 UTC
```
ignorekickmessage=true
...
[AutoRelog]
enabled=true
delay=30
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt
```

i have enabled my auto reconnect for my console client, but sometimes it stuck at "[Logging in...](https://prnt.sc/vg5vd3)" forever and nothing happens unless i close the client and open it again.

is there any possible way to fix this? like set a timeout for every x seconds if something like this happens or disconnecting and reconnect it again?

**Comment by ORelio** [comment] 2020-11-09 18:47
Seems similar to #1292 although I could not reproduce yet.

**Comment by tunkusalim** [comment] 2020-11-10 05:44
well, it wasnt stuck on checking sessions like #1292 , but at the "Logging in...". 
and its usually happens after the server reboot/restart (or something similar which kicked all players).

**Comment by cubic86** [comment] 2020-11-18 10:32
I have exactly same issue. Everything was working fine and now it seems to be permanently stuck on "Logging in...". I am not using any auto reconnect (I start the client manually).

**Comment by cubic86** [comment] 2020-11-18 10:55
```
Console Client for MC 1.4.6 to 1.16.3 - v1.16.3 - By ORelio & Contributors                                                                                                                                                                                                     ﻿﻿
[MCC] [Settings] Loading Settings from XXX
Resolving XXX...
Found server XXX for domain XXX
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
[SessionCache] Initializing FileSystemWatcher for file: /XXX/Minecraft-Console-Client/MinecraftClient/bin/Release/SessionCache.ini
Loading session cache from disk: SessionCache.ini
Loaded session: XXX
Loaded session: XXX
Session data has been successfully loaded from disk.
Performing request to authserver.mojang.com
Connected to proxy XXX
> POST /validate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.16.3
> Content-Type: application/json
> Content-Length: 389
> Connection: close
> 
> {"accessToken": "XXX", "clientToken": "XXX" }

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Wed, 18 Nov 2020 10:51:55 GMT
< Server: Restlet-Framework/2.4.1
< X-Cache: Miss from cloudfront
< Via: 1.1 XXX.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: CDG3-C1
< X-Amz-Cf-Id: XXX
< 
< 
Cached session is still valid for XXX.
Success. (session ID: XXX)
Using Minecraft version 1.16.3 (protocol v753)
[MCC] [ScriptScheduler] Loading tasks from '/home/ubuntu/apps/Minecraft-Console-Client/MinecraftClient/bin/Release/tasks-new.ini'
[MCC] [ScriptScheduler] Loaded task:
 triggeronfirstlogin = True
 triggeronlogin = False
 triggerontime = False
 triggeroninterval = False
 timevalue = 
 timeinterval = 0
 action = XXX
Translations file loaded.
Version is supported.
Logging in...
```
I removed the session infos from the log.

**Comment by cubic86** [comment] 2020-11-18 11:09
I made a full restart of the machine, still the same thing happens. I'm running the MCC from mono under Ubuntu.

**Comment by cubic86** [comment] 2020-11-18 11:14
Thread dump:
```
"<threadpool thread>"
"Finalizer"
"<unnamed thread>"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.IO.InotifyWatcher.ReadFromFD (intptr,byte[],intptr) <0x0007f>
  at System.IO.InotifyWatcher.Monitor () <0x00073>
  at System.Threading.ThreadHelper.ThreadStart_Context (object) <0x00099>
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00178>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00020>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) <0x00059>
  at System.Threading.ThreadHelper.ThreadStart () <0x0002e>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0x000d1>

"<unnamed thread>"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Net.Sockets.Socket.Receive_internal (intptr,byte[],int,int,System.Net.Sockets.SocketFlags,int&) <0x00082>
  at System.Net.Sockets.Socket.Receive_internal (System.Net.Sockets.SafeSocketHandle,byte[],int,int,System.Net.Sockets.SocketFlags,int&) <0x00057>
  at System.Net.Sockets.Socket.Receive_nochecks (byte[],int,int,System.Net.Sockets.SocketFlags,System.Net.Sockets.SocketError&) <0x00053>
  at System.Net.Sockets.Socket.Receive (byte[],int,int,System.Net.Sockets.SocketFlags) <0x0006f>
  at MinecraftClient.Protocol.Handlers.SocketWrapper.Receive (byte[],int,int,System.Net.Sockets.SocketFlags) <0x00093>
  at MinecraftClient.Protocol.Handlers.SocketWrapper.ReadDataRAW (int) <0x0004b>
  at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextVarIntRAW (MinecraftClient.Protocol.Handlers.SocketWrapper) <0x00033>
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.ReadNextPacket (int&,System.Collections.Generic.Queue`1<byte>) <0x00047>
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.Login () <0x0027f>
  at MinecraftClient.McClient.StartClient (string,string,string,string,uint16,int,MinecraftClient.Protocol.Handlers.Forge.ForgeInfo,bool,string) <0x00a3e>
  at MinecraftClient.McClient..ctor (string,string,string,int,MinecraftClient.Protocol.Handlers.Forge.ForgeInfo,string,uint16) <0x004fb>
  at MinecraftClient.Program.InitializeClient () <0x00b87>
  at MinecraftClient.Program.Main (string[]) <0x008ab>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0x000d1>
```

**Comment by ReinforceZwei** [comment] 2020-11-18 14:04
According to MS Docs about the `Socket.Receive` method,
> If no data is available for reading, the Receive method will block until data is available, unless a time-out value was set by using Socket.ReceiveTimeout.

and the thread dump from @cubic86 , my guess is there is no data available for read in the `Login()` procedure and hence blocked the program. Additionally there is no `Socket.ReceiveTimeout` set in `Protocol18.cs`. 

I don't know how to test it, so everything are just theory.

**Comment by cubic86** [comment] 2020-11-18 15:22
You can try to log in to play.minesuperior.com. I can reproduce it from each of my machines.

**Comment by ReinforceZwei** [comment] 2020-11-22 13:12
I am able to recreate the "Logging in..." stuck by using the following code. 
![image](https://user-images.githubusercontent.com/39955851/99904536-5ab81800-2d06-11eb-9954-727abb8c3597.png)
Please note that I disabled the MCC server ping function by setting these two settings.
```ini
mcversion=1.15.2
mcforge=false 
```

After adding:
```cs
client.ReceiveTimeout = 10 * 1000; // 10 seconds
```
The client was able to timeout instead of stuck forever.

**Comment by ORelio** [comment] 2020-11-27 21:18
Good catch @ReinforceZwei, merged your PR 👍

**Closed** 2020-11-27 21:17 UTC
Labels: a:bug, in:connect-to-server, waiting-for:more-info
