### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [ORelio/Minecraft-Console-Client#666] opened 2019-03-11 19:03 UTC
The crash is Dutch. http://prntscr.com/mwgxk5

I'm able to join the other server but when I do /factions it just throws that error and closes the program

**Comment by TheSnoozer** [comment] 2019-03-17 02:08
I'm closing this as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379 since I'm actually not sure if there is any benefit of keeping the same set of issues around. Sadly not sure what causes it :/

**Closed by TheSnoozer** 2019-03-17 02:08 UTC
Labels: rejected:duplicate
