### ISSUE TITLE
Session Errors

### ISSUE THREAD

**Issue by Ali1892** [ORelio/Minecraft-Console-Client#955] opened 2020-04-21 02:10 UTC
Hi so, I am running Multiple Alts and keep running into session errors which are making it useless.
I've tried booting one alt at a time and sometimes they run into the same issue.

Screenshot:
https://i.imgur.com/xwfnjlO.png

**Comment by MatrixSystemPVP** [comment] 2020-04-21 07:47
I think that the error is from mojangs site not from the console client. I have also sometimes the error but the i wait like 5mins and try again. The most times it works. I think its because soo many people are at home and tying to login to minecraft.

**Comment by Gateswong** [comment] 2020-04-21 10:51
You need to get latest build from 
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by ORelio** [comment] 2020-04-21 18:00
You are not using the latest build, your issue was fixed in commit 52248d1abaf9b03047f90caa465f5f0b466f7c56. Duplicate of #951.

**Closed by ORelio** 2020-04-21 18:00 UTC
