### ISSUE TITLE
Inventory Handling problem

### ISSUE THREAD

**Issue by Heringen** [ORelio/Minecraft-Console-Client#1600] opened 2021-05-22 01:11 UTC
So im trying to make inventory handling enabled but it won't work ([MCC] Please enable InventoryHandling in the config file first.)

I tried putting inventoryhandling=true/inventoryhandling=enabled under both main and mc settings, and tried adding seperate column with 
[InventoryHandling]
enabled=true
But noone seems to work.
How and where should i type it? Thanks in advance!

Warm regards.

**Comment by ReinforceZwei** [comment] 2021-05-22 09:17
Inventory handling only support Minecraft version 1.10 and afterward.

**Comment by ORelio** [comment] 2021-05-22 09:26
As stated by @ReinforceZwei, inventory handling will not work for older Minecraft versions, but a message in console should tell you that inventory handling is not supported for your server's version. Possible duplicate of #929

**Comment by Heringen** [comment] 2021-05-22 14:06
Oh okay.
Will it work for older version somwhere in future?

**Comment by ORelio** [comment] 2021-05-22 14:47
Cannot provide an ETA but there is a feature request open here: #929

**Comment by Heringen** [comment] 2021-05-22 15:45
Aight, ty for clarification!

**Closed** 2021-05-23 21:10 UTC
Labels: a:question, in:inventory-handling, resolved
