### ISSUE TITLE
New Issue: Checking session failed

### ISSUE THREAD

**Issue by CoderStone** [ORelio/Minecraft-Console-Client#960] opened 2020-04-22 06:04 UTC
This issue started popping up again, the very common 
![image](https://user-images.githubusercontent.com/34324909/79946260-97a0f100-843d-11ea-915b-5291ec70af16.png)

Any ideas? Until yesterday it was working fine, but now every single time I log in, this happens. Was there an authentication server downtime, or Mojang updated their filters again?

**Comment by DateNogg** [comment] 2020-04-22 07:18
Same issue for me since last day

**Comment by JeffHolliday** [comment] 2020-04-22 08:02
Same Issue on my side.

**Comment by Cracch** [comment] 2020-04-22 08:25
I have had the same issue, it started around 1am pst Monday.

**Comment by Cracch** [comment] 2020-04-22 08:32
downloading the latest version and then pasting it over my old client worked for me.

**Comment by Forssmark** [comment] 2020-04-22 09:49
I have posted this twice now but both times being said to use the latest version which I'm doing it still says failed to log in.

**Comment by swaggyjj** [comment] 2020-04-22 12:08
> downloading the latest version and then pasting it over my old client worked for me.

This worked for me also

**Comment by JeffHolliday** [comment] 2020-04-22 16:29
[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\AlphaCypher\script.txt'

It "worked" for me but keeps saying this comment in the console

**Comment by JeffHolliday** [comment] 2020-04-22 16:46
I got mine to start working again but when I launch the console it now spams this,

[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\Alts\AlphaCypher\script.txt'
[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\Alts\AlphaCypher\script.txt'
[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\Alts\AlphaCypher\script.txt'
[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\Alts\AlphaCypher\script.txt'
[MCC] [Script] File not found: 'C:\Users\anobi\Desktop\Alts\AlphaCypher\reconnect.txt'

Any idea what scipt.txt it is trying to find and how to fix?

**Comment by MattiasMoenster2019** [comment] 2020-04-22 22:10
I am also having this problem NOTHING seems to fix it.
Have downloaded the latest version but it just stops working after a good 2 runs

**Comment by JeffHolliday** [comment] 2020-04-23 01:30
I added a random file called script.txt and reconnect.txt and it seemed to fix it.

**Comment by ORelio** [comment] 2020-04-24 10:41
Seems like a duplicate of #951. Are you sure you are using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?
If so, retry with `debugmessages=true` in config and post full output. Thanks.

**Comment by MattiasMoenster2019** [comment] 2020-04-24 14:02
I am 100% sure I am using the latest build and ill try getting the debug

**Comment by MattiasMoenster2019** [comment] 2020-04-24 23:48
Connection has been lost.
23:08:12 [MCC] [AutoRelog] Got disconnected with message: Connection has been lost.
23:08:12 [MCC] [AutoRelog] Message contains 'connection has been lost'. Reconnecting.
23:08:12 [MCC] [AutoRelog] Waiting 5 seconds before reconnecting...
23:08:17 [MCC] [AutoRelog] Disconnecting and Reconnecting to the Server
23:08:17 [MCC] [AutoRelog] Disconnection initiated by User or MCC bot. Ignoring.
Restarting Minecraft Console Client...
23:08:18 Performing request to authserver.mojang.com
23:08:18 > POST /validate HTTP/1.1
23:08:18 > Host: authserver.mojang.com
23:08:18 > User-Agent: MCC/1.15.2
23:08:18 > Content-Type: application/json
23:08:18 > Content-Length: 409
23:08:18 > Connection: close
23:08:18 >
23:08:18 > {"accessToken": "eyJhbGciOiJIUzI1NiJ9\u002eeyJzdWIiOiJjYWVmZjRjMTY0ZTY3NzQ1OTk4MjZjYWFlZjZjMzE2OCIsInlnZ3QiOiI2ZWZiZWI5MmMzMmU0MmEyYjJiZmE1ZGI2MjNkYjdlMSIsInNwciI6ImNmOTc0YjQ1MzdhNDRiMzA5N2UwODkwODlmZWZlYjM1IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc3NjYwNjksImlhdCI6MTU4NzU5MzI2OX0\u002ebtEwSeE\u002dFI\u002dfKUsOA\u005f\u002d2tU6NB08WOnftBV99YKmPjJI", "clientToken": "cfb9d8fcdf78457189d43e31cdc767ee" }

23:08:18 < HTTP/1.1 204 No Content
23:08:18 < Connection: close
23:08:18 < Accept-Ranges: bytes
23:08:18 < Date: Fri, 24 Apr 2020 21:08:18 GMT
23:08:18 < Server: Restlet-Framework/2.4.1
23:08:18 < X-Cache: Miss from cloudfront
23:08:18 < Via: 1.1 a14ac175c5535de44ce87bfddfa7ddbf.cloudfront.net (CloudFront)
23:08:18 < X-Amz-Cf-Pop: CPH50-C1
23:08:18 < X-Amz-Cf-Id: QSsvdYbv7gZrex23_08_IGQNLbz5sHr2uTWyZNxkHv6_NacV5z8FTA==
23:08:18 <
23:08:18 <
23:08:18 Cached session is still valid for DunH1tM3.
Success. (session ID: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYWVmZjRjMTY0ZTY3NzQ1OTk4MjZjYWFlZjZjMzE2OCIsInlnZ3QiOiI2ZWZiZWI5MmMzMmU0MmEyYjJiZmE1ZGI2MjNkYjdlMSIsInNwciI6ImNmOTc0YjQ1MzdhNDRiMzA5N2UwODkwODlmZWZlYjM1IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc3NjYwNjksImlhdCI6MTU4NzU5MzI2OX0.btEwSeE-FI-fKUsOA_-2tU6NB08WOnftBV99YKmPjJI)
23:08:18 Using Minecraft version 1.8 (protocol v47)
23:08:18 Inventories are currently not handled for that MC version.
Version is supported.
Logging in...
23:08:18 Crypto keys & hash generated.
Checking Session...
23:08:18 Performing request to sessionserver.mojang.com
23:08:18 > POST /session/minecraft/join HTTP/1.1
23:08:18 > Host: sessionserver.mojang.com
23:08:18 > User-Agent: MCC/1.15.2
23:08:18 > Content-Type: application/json
23:08:18 > Content-Length: 432
23:08:18 > Connection: close
23:08:18 >
23:08:18 > {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYWVmZjRjMTY0ZTY3NzQ1OTk4MjZjYWFlZjZjMzE2OCIsInlnZ3QiOiI2ZWZiZWI5MmMzMmU0MmEyYjJiZmE1ZGI2MjNkYjdlMSIsInNwciI6ImNmOTc0YjQ1MzdhNDRiMzA5N2UwODkwODlmZWZlYjM1IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODc3NjYwNjksImlhdCI6MTU4NzU5MzI2OX0.btEwSeE-FI-fKUsOA_-2tU6NB08WOnftBV99YKmPjJI","selectedProfile":"cf974b4537a44b3097e089089fefeb35","serverId":"a15e7641fc111ca65a87e43c0381da5085c3411"}

23:08:18 < HTTP/1.1 403 Forbidden
23:08:18 < Server: CloudFront
23:08:18 < Date: Fri, 24 Apr 2020 21:08:18 GMT
23:08:18 < Content-Type: text/html
23:08:18 < Content-Length: 919
23:08:18 < Connection: close
23:08:18 < X-Cache: Error from cloudfront
23:08:18 < Via: 1.1 0562d7d213bde9a129ec458c631f9cef.cloudfront.net (CloudFront)
23:08:18 < X-Amz-Cf-Pop: CPH50-C1
23:08:18 < X-Amz-Cf-Id: H3965xypvTqJb8sN1yqFoQ9TYPmVDdokaVgDTy7d2E2cic9RDNKIdg==
23:08:18 <
23:08:18 < <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
23:08:18 < <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
23:08:18 < <TITLE>ERROR: The request could not be satisfied</TITLE>
23:08:18 < </HEAD><BODY>
23:08:18 < <H1>403 ERROR</H1>
23:08:18 < <H2>The request could not be satisfied.</H2>
23:08:18 < <HR noshade size="1px">
23:08:18 < Request blocked.
23:08:18 < We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
23:08:18 < <BR clear="all">
23:08:18 < If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
23:08:18 < <BR clear="all">
23:08:18 < <HR noshade size="1px">
23:08:18 < <PRE>
23:08:18 < Generated by cloudfront (CloudFront)
23:08:18 < Request ID: H3965xypvTqJb8sN1yqFoQ9TYPmVDdokaVgDTy7d2E2cic9RDNKIdg==
23:08:18 < </PRE>
23:08:18 < <ADDRESS>
23:08:18 < </ADDRESS>
23:08:18 < </BODY></HTML>
Login failed :
23:08:18 Failed to check session.
23:08:18 Not connected to any server. Use '/help' for help.
23:08:18 Or press Enter to exit Minecraft Console Client.

**Comment by MattiasMoenster2019** [comment] 2020-04-24 23:48
That is from the moment it disconnects

**Comment by ORelio** [comment] 2020-04-25 11:49
`HTTP/1.1 403 Forbidden` means that the login servers are blocking you from logging in.
The issue does not seems to be inside MCC... Your IP address might be blacklisted.

**Closed** 2020-11-27 21:29 UTC
Labels: a:bug, in:mojang-api, rejected:invalid
