### ISSUE TITLE
 Inventory Handling Error

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#914] opened 2020-03-31 06:20 UTC
mcversion=1.15.2 # Use 'auto' or '1.X.X' values
brandinfo=mcc # Use 'mcc','vanilla', or 'none'
enableentityhandling=true # Toggle entities handling
terrainandmovements=true # Uses more ram, cpu, bandwidth
inventoryhandling=true # Toggle inventory handling (experimental, enable only for development)
![image](https://user-images.githubusercontent.com/35975332/77993359-70289e00-7341-11ea-9544-20b06a006982.png)
![image](https://user-images.githubusercontent.com/35975332/77993450-a2d29680-7341-11ea-904b-483555177b3f.png)

mcversion=1.8.9 # Use 'auto' or '1.X.X' values
![image](https://user-images.githubusercontent.com/35975332/77993326-5c7d3780-7341-11ea-9c5d-09ee6fa381f2.png)

**Comment by ORelio** [comment] 2020-03-31 08:58
What build are you using? The `/inventory` command is translated in Russian, which is not standard.

**Comment by Nekiplay** [comment] 2020-03-31 10:15
> What build are you using? The `/inventory` command is translated in Russian, which is not standard.

Last https://github.com/ORelio/Minecraft-Console-Client/commit/5d0172a1f9e778f6ef306f9fd55ab68a90728c7a

**Comment by Nekiplay** [comment] 2020-03-31 10:36
mcversion=1.15.2                     # Use 'auto' or '1.X.X' values
enableentityhandling=true         # Toggle entities handling
[AutoAttack]
# Entity Handling NEED to be enabled first
enabled=true
![image](https://user-images.githubusercontent.com/35975332/78017236-62850f80-7365-11ea-8ed9-89ab451e860c.png)

**Comment by ORelio** [comment] 2020-03-31 10:39
Seems like a calculation issue in [AutoAttack](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/AutoAttack.cs#L88) @ReinforceZwei

**Comment by ReinforceZwei** [comment] 2020-03-31 10:58
I couldn't reproduce this bug and I can't read the exception message because I don't understand Russian. I cannot debug :cry:

**Comment by Nekiplay** [comment] 2020-03-31 12:14
https://youtu.be/Y6ljwJYYeQc

**Comment by ReinforceZwei** [comment] 2020-03-31 12:31
Entity handling don't work on Minecraft version 1.12.2 or below.
Console will automatically disable entity handling when version unsupported.
Are you using the latest version of build?

**Comment by Nekiplay** [comment] 2020-03-31 12:38
> Entity handling don't work on Minecraft version 1.12.2 or below.
> Console should automatically disable entity handling when version unsupported.
> ~Are you using the latest version of build?~ I saw it now.
> I found the bug and I will push it ASAP.

https://youtu.be/wAaPTvKS5to 1.12.2 Minecraft Version not fixed

**Comment by Nekiplay** [comment] 2020-03-31 12:40
> Entity handling don't work on Minecraft version 1.12.2 or below.
> Console should automatically disable entity handling when version unsupported.
> ~Are you using the latest version of build?~ I saw it now.
> I found the bug and I will push it ASAP.


I am always happy to help, I hope entity handling will be supported in other versions.

**Comment by ReinforceZwei** [comment] 2020-03-31 12:41
Seems like I made a mistake in version comparing :P

**Comment by Nekiplay** [comment] 2020-03-31 12:43
> Seems like I made a mistake in version comparing :P


Can I find out your Discord together we can come up with a lot of ideas and I can help than I can not so long ago I study C # but I think I can help

**Comment by ReinforceZwei** [comment] 2020-03-31 12:49
Sure, but I may not put much effort on this project as before since I am getting more busy now.

**Comment by Nekiplay** [comment] 2020-03-31 12:52
> Sure, but I may not put much effort on this project as before since I am getting more busy now.

I hope you do not quit developing this project

**Comment by ReinforceZwei** [comment] 2020-03-31 12:53
I will leave my Discord here: Reinforce II#9963

**Comment by ORelio** [comment] 2020-03-31 13:41
We're lacking contributors, thats why features are added very slowly. Glad to see some activity lately 🙂

**Comment by ORelio** [comment] 2020-04-01 20:14
All the issues reported here should be fixed as per commits 5d0172a1f9e778f6ef306f9fd55ab68a90728c7a and dbe02c063c12fe88930d86a98f823a6875ecbc4b

**Closed by ORelio** 2020-04-01 20:14 UTC
