### ISSUE TITLE
Connecting to discord

### ISSUE THREAD

**Issue by BottNet** [ORelio/Minecraft-Console-Client#620] opened 2019-01-06 21:10 UTC
Hello there,

I was wondering if there is a way to connect a discord bot with the Minecraft Console Client. I would ideally like it to relay messages too and from discord. E.g. I type clear in chat and it will send a message to discord saying clear.

**Comment by TheSnoozer** [comment] 2019-01-07 14:06
related to https://github.com/ORelio/Minecraft-Console-Client/issues/258

```
someone needs to develop a library (some code) for interacting with it
```

**Comment by Sharpen-Up** [comment] 2019-01-09 09:54
This is probably as close to what your wanting as your going to get "cosmic-console-client-discord-bot" give it a google.
Haven't had any luck getting the two bot's it comes with to function properly. Can load up discordBot and get it to display and behave when manually populating files (boring xD) hence the function of the bots.
Doesn't use an API of sorts, combo of .txt file retrieval and pastebin API for sharing of Logs (generally long files)
If anyone experienced had a spare minute to examine this configuration and share a solution or thoughts to what may have changed between releases to break it. (Feb 19, 2018 instructional post was made)

**Comment by BottNet** [comment] 2019-01-10 14:16
> This is probably as close to what your wanting as your going to get "cosmic-console-client-discord-bot" give it a google.
> Haven't had any luck getting the two bot's it comes with to function properly. Can load up discordBot and get it to display and behave when manually populating files (boring xD) hence the function of the bots.
> Doesn't use an API of sorts, combo of .txt file retrieval and pastebin API for sharing of Logs (generally long files)
> If anyone experienced had a spare minute to examine this configuration and share a solution or thoughts to what may have changed between releases to break it. (Feb 19, 2018 instructional post was made)

**Comment by BottNet** [comment] 2019-01-10 14:19
Sharpen-UP. I have taken a look at that and run through the little guide it comes with. However, all seems to work but the Console client is just running into constant issues, the the point where it's constantly failing to login. 

If anyone has any ideas as to why the console client isn't working that would be great? Like I have used the same coding inside the Minecraft.ini and pasted into one of my Console clients that was previously working and it continued to work? So I am extremely confused as to what's causing the issues here?

**Comment by Sharpen-Up** [comment] 2019-01-11 05:58
> Sharpen-UP. I have taken a look at that and run through the little guide it comes with. However, all seems to work but the Console client is just running into constant issues, the the point where it's constantly failing to login.
> 
> If anyone has any ideas as to why the console client isn't working that would be great? Like I have used the same coding inside the Minecraft.ini and pasted into one of my Console clients that was previously working and it continued to work? So I am extremely confused as to what's causing the issues here?

Need to upgrade to latest CC dev "Minecraft.exe" then the real problem solving begins...

**Comment by Sharpen-Up** [comment] 2019-01-14 07:22
Did this get console client running?

**Comment by TheSnoozer** [comment] 2019-03-17 02:22
Closing as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/258.

If you have any other issues that are related to using this client (and not one randomly found on the internet), feel free to open a new issue.

**Closed by TheSnoozer** 2019-03-17 02:22 UTC
Labels: rejected:duplicate
