### ISSUE TITLE
Respond to Confirm Transaction Packets

### ISSUE THREAD

**Issue by Rerd** [ORelio/Minecraft-Console-Client#1324] opened 2020-11-10 05:43 UTC
The console client should respond to Confirm Transaction packets. Some anti-cheats use them to detect lag and if a client does not respond to them, they will be kicked from the server.

**Comment by ReinforceZwei** [comment] 2020-11-10 06:00
It was implemented. Please see [Protocol18.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#767)

**Comment by Rerd** [comment] 2020-11-10 06:26
Still getting timed out for not responding to transactions. It should be packet ID 0x32 for 1.8.x at least

**Comment by ReinforceZwei** [comment] 2020-11-10 06:29
You will need inventory handling enabled for it to work.

**Comment by Rerd** [comment] 2020-11-10 06:32
I enabled inventory handling, still getting kicked.

**Comment by ReinforceZwei** [comment] 2020-11-10 07:38
Look like you had mentioned 1.8.x. Unfortunately inventory handling doesn't support 1.8 at the time.

**Comment by Rerd** [comment] 2020-11-10 19:11
Are there any plans on support for 1.8 inventory handling?

**Comment by ReinforceZwei** [comment] 2020-11-11 00:18
Honestly, no. I don't have time to implement new features now.

**Comment by ReinforceZwei** [comment] 2021-05-02 09:14
Duplicate of #997

**Closed** 2021-05-02 12:23 UTC
Labels: a:enhancement, in:inventory-handling, rejected:duplicate
