### ISSUE TITLE
Hold down right click.

### ISSUE THREAD

**Issue by KeanuNys** [ORelio/Minecraft-Console-Client#538] opened 2018-08-07 01:18 UTC
Is there a way to make the player hold down the right click button? In other words, the "Use Item/Place Block" button as it's called in the controls page.

**Comment by ORelio** [comment] 2018-08-08 14:33
Currently, no such thing is implemented.

**Comment by ORelio** [comment] 2018-11-15 19:55
Closing as duplicate of #171

**Closed by ORelio** 2018-11-15 19:55 UTC
