### ISSUE TITLE
Console client disconnecting at random times for no reason.

### ISSUE THREAD

**Issue by justdepression** [ORelio/Minecraft-Console-Client#830] opened 2019-11-22 20:17 UTC
So basically, when I try to use a console client, it for 30 minutes to up 5 hours. Then it says  "Connection has been lost" I do use a VPS but the connection doesn't get shut off. My settings are below. If anyone could help me with this issue I would be very grateful, my discord is Depression#1893

```ini
# Minecraft Console Client v1.12.2 DEV
# Startup Config File

[Main]

# General settings
# Leave blank to prompt user on startup
# Use "-" as password for offline mode

login=
password=
serverip=play.saicopvp.com

# Advanced settings

language=en_GB
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash              # Use 'none', 'slash' or 'backslash'
splitmessagedelay=2                # Seconds between each part of a long message
botowners=Player1,Player2,Player3  # Use name list or myfile.txt with one name per line
botmessagedelay=2                  # Seconds to delay between message a bot makes to avoid accidental spam
mcversion=1.8.9                    # Use 'auto' or '1.X.X' values
brandinfo=mcc                      # Use 'mcc','vanilla', or 'none'
chatbotlogfile=                    # Leave empty for no logfile
privatemsgscmdname=tell            # Used by RemoteControl bot
showsystemmessages=true            # System messages for server ops
showxpbarmessages=true             # Messages displayed above xp bar
showchatlinks=true                 # Show links embedded in chat messages
terrainandmovements=false          # Uses more ram, cpu, bandwidth
sessioncache=disk                  # How to retain session tokens. Use 'none', 'memory' or 'disk'
resolvesrvrecords=fast             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.
accountlist=accounts.txt           # See README > 'Servers and Accounts file' for more info about this file
serverlist=servers.txt             # See README > 'Servers and Accounts file' for more info about this file
playerheadicon=true                # Only works on Windows XP-8 or Windows 10 with old console
exitonfailure=false                # Disable pauses on error, for using MCC in non-interactive scripts
debugmessages=false                # Please enable this before submitting bug reports. Thanks!
scriptcache=true                   # Cache compiled scripts for faster load on low-end devices
timestamps=false                   # Prepend timestamps to chat messages

[AppVars]
# yourvar=yourvalue
# can be used in some other fields as %yourvar%
# %username% and %serverip% are reserved variables.

[Proxy]
enabled=false                      # Use 'false', 'true', or 'login' for login only
type=HTTP                          # Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000                # Proxy server must allow HTTPS for login, and non-443 ports for playing
username=                          # Only required for password-protected proxies
password=                          # Only required for password-protected proxies

[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=true                      # MCC built-in support for common message formats
# public=^<([a-zA-Z0-9_]+)> (.+)$
# private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
# tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

[MCSettings]
enabled=true                       # If disabled, settings below are not sent to the server
locale=en_US                       # Use any language implemented in Minecraft
renderdistance=medium              # Use tiny, short, medium, far, or chunk amount [0 - 255]
difficulty=normal                  # MC 1.7- difficulty. peaceful, easy, normal, difficult
chatmode=enabled                   # Use 'enabled', 'commands', or 'disabled'. Allows to mute yourself...
chatcolors=true                    # Allows disabling chat colors server-side
main_hand=left                     # MC 1.9+ main hand. left or right
skin_cape=true
skin_hat=true
skin_jacket=false
skin_sleeve_left=false
skin_sleeve_right=false
skin_pants_left=false
skin_pants_right=false
# Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=true
delay=600 #10 = 1s
command=/server guardian

[AutoRelog]
enabled=true
delay=10
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=false
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini
```

**Comment by ORelio** [comment] 2019-11-22 20:21
This is a known issue with the Mono framework, but yet the root cause could not be found. Currently, the best you can do as a workaround is using AutoRelog to relog when this happen since MCC now implements auto-timeout as per #802

**Comment by Nekiplay** [comment] 2019-12-27 21:35
I give the bot a block, the item is transferred to the local server, the bot gives an error version 1.12.2
https://ibb.co/GQKDDvY

**Comment by ORelio** [comment] 2021-05-21 18:58
Seems related to #1303 - As part of issue cleanup, I'll close this one in favour of the other one.

**Closed by ORelio** 2021-05-21 18:58 UTC
Labels: a:bug, in:connect-to-server, on:linux
