### ISSUE TITLE
SpawnEntity Crash

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1239] opened 2020-08-26 23:58 UTC
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

Version 1.15.2
![image](https://user-images.githubusercontent.com/35975332/91368222-f201f200-e821-11ea-8bf7-6870345784dc.png)
Strange, again, after restarting, I did not encounter an error.

**Comment by ReinforceZwei** [comment] 2020-08-27 01:42
Maybe there's some race condition?

**Comment by Nekiplay** [comment] 2020-08-27 02:32
It seems to me that this happened because Entity was null.

**Comment by ORelio** [comment] 2020-08-27 17:34
Was it fixed in #1241?

**Comment by Nekiplay** [comment] 2020-08-28 10:23
> Was it fixed in #1241?
No

**Comment by Vort** [comment] 2020-12-16 07:25
Do not see this problem.
Any specific steps needed to reproduce it?

![image](https://user-images.githubusercontent.com/1242858/102317628-8d110a00-3f80-11eb-9250-0dbabf83c46b.png)

**Comment by ORelio** [comment] 2021-05-21 18:55
Unfortunately we could not reproduce this issue.

**Closed by ORelio** 2021-05-21 18:55 UTC
Labels: a:bug, in:entity-handling
