### ISSUE TITLE
How do I run MCC 24/7 with a VPS or something, even when my PC is off?

### ISSUE THREAD

**Issue by AayanTDE** [ORelio/Minecraft-Console-Client#1427] opened 2021-01-25 06:12 UTC

**Comment by ReinforceZwei** [comment] 2021-01-25 06:15
Duplicate of #1408

**Closed by ReinforceZwei** 2021-01-25 06:15 UTC
Labels: a:question

**Comment by ReinforceZwei** [comment] 2021-01-25 06:16
See https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use for how to run MCC on linux.
