### ISSUE TITLE
[BUG] System.Net.Sockets.SocketExeception : An existing connection was forcibly closed by the remote host Error

### ISSUE THREAD

**Issue by YellySmelly** [ORelio/Minecraft-Console-Client#1777] opened 2021-09-30 21:46 UTC
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

Latest

### Expected Behavior

I expect to be able to use the console client without this bug

### Actual Behavior

I keep getting this bug that says System.Net.Sockets.SocketExeception : An existing connection was forcibly closed by the remote host 

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

![](https://cdn.discordapp.com/attachments/813172635848409128/892968441865179207/unknown.png)

### Anythings that could help diagnosing the bug

```txt
I restarted my pc and then this happened when I tried to open the console client
```

### Device

Desktop

### Operating System

Windows

**Comment by HexedHero** [comment] 2021-09-30 22:01
Related to #1774

**Comment by YellySmelly** [comment] 2021-09-30 22:14
I have looked into this and many other people are having this problem. Lmk if anyone has any fixes

**Comment by ReinforceZwei** [comment] 2021-10-01 04:16
Duplicate of #1774

**Closed by ReinforceZwei** 2021-10-01 04:16 UTC
Labels: a:bug
