### ISSUE TITLE
Water not pushing player. 

### ISSUE THREAD

**Issue by Zxpphire** [ORelio/Minecraft-Console-Client#656] opened 2019-03-02 21:29 UTC
I have terrain and movements on and I make the bot move down towards my afk pool. When it’s inside, the water won’t push it. I am assuming this is because fly on the server is enabled and you can’t be pushed while you are flying. Is there a way for me to turn off flying such as how you do in a normal game, by double tapping space bar.

**Comment by Mhowser** [comment] 2019-03-02 21:59
Did you try typing /fly or /send /fly?

**Comment by Zxpphire** [comment] 2019-03-03 05:30
Yes, the water still won’t push me

**Comment by Mhowser** [comment] 2019-03-03 05:45
What version is the server? If it's 1.13+ terrainmovements is effectively
disabled due to the world format not being "understandable" to the console
client.

**Comment by Zxpphire** [comment] 2019-03-03 11:43
Version runs on 1.8.9, i can do /move perfectly fine

**Comment by TheSnoozer** [comment] 2019-03-17 01:59
Duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/206

**Closed by TheSnoozer** 2019-03-17 01:59 UTC
Labels: rejected:duplicate

**Comment by CADonAFK** [comment] 2021-12-28 17:48
I need help I have a afk bot but it does not move

**Comment by ORelio** [comment] 2021-12-28 17:50
@CADonAFK: See https://github.com/MCCTeam/Minecraft-Console-Client/issues/206#issuecomment-251961828

**Comment by CADonAFK** [comment] 2021-12-28 19:01
Huh can you just tell me the answer pls

**Comment by CADonAFK** [comment] 2021-12-28 19:10
Oh I still can’t type /move in chat it won’t let me it has a error

**Comment by ORelio** [comment] 2021-12-28 21:09
Water will not move the player. Use another AFK mechanism. Please open your own issue if you have a different error.

**Comment by CADonAFK** [comment] 2021-12-28 21:19
What anothe afk thing should I use for the afk boy
