### ISSUE TITLE
Login failing

### ISSUE THREAD

**Issue by PrismaticYT** [ORelio/Minecraft-Console-Client#366] opened 2017-12-30 13:07 UTC
It just says invalid password.

Debug data:

Debug: Login Request: {"agent": { "name": "Minecraft", "version": 1 }, "username": "HellToTheFuckNo", "password": "FuckYouYou'reNotGettingMyPassword", "clientToken": "FuckOffMateYouAren'tGettingThisEither" }

**Comment by ORelio** [comment] 2017-12-30 21:17
VPS blacklist? See #359

**Comment by PrismaticYT** [comment] 2017-12-31 04:55
I'm not using a VPS..

**Comment by ORelio** [comment] 2017-12-31 11:48
In that case, please include the `Debug: Login Response:` line. Also make sure you can login using the regular Minecraft game (too many logins will also cause this error).

**Comment by PrismaticYT** [comment] 2018-01-01 05:36
I can login with the normal game, and there is no login response line.

**Comment by TheSnoozer** [comment] 2019-09-20 15:46
Since this seems to be a very old issue, I would suggest to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try if the problem is still present.

**Comment by ORelio** [comment] 2019-12-19 18:48
Closing this report as it is quite old and does not contain enough info.

**Closed by ORelio** 2019-12-19 18:48 UTC
Labels: a:bug, in:connect-to-server, rejected:invalid
