### ISSUE TITLE
Crashes when joining sub server

### ISSUE THREAD

**Issue by Tonitohoru** [ORelio/Minecraft-Console-Client#1495] opened 2021-03-06 17:55 UTC
**Prerequisites**
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ ] I have set `debugmessages=true` in config to diagnose my issue
 - [ ] I have redacted session tokens and passwords before attaching screenshots

---
## Expected Behavior

---
## Actual Behavior

---
## Steps to Reproduce the Problem

  1. Login to [...] server
  2. Use [...] command
  3.

---
## Screenshot (If applicable)

---
## Anythings that could help diagnosing the bug
(config, log output)

Joining the server is fine. You will join in a hub.
There i do /server F1 and enter the sub server. The bot survives 1 second and then crashes
(It doesn't really crash. It just stops receiving any more messages and the player disconnects, while the window stays the same)

---
## Specifications

  - Console Client version:  latest
  - Device: (Desktop, Laptop, VPS, Raspberry Pi, etc) VPS
  - Operating System: Debian
  - Minecraft version: Tried all
  - Server address (If applicable):

**Comment by Tonitohoru** [comment] 2021-03-06 18:11
The account disconnects at around 20 seconds

**Comment by ORelio** [comment] 2021-03-06 20:36
Hi,
Silent disconnections on Mono are a recurring issue:
https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue+silent+disconnect
We never found out the cause and we suspect it is a bug in Mono itself because Microsoft .NET does not have this.
Unfortunately we have no real fix for this. Here is a similar issue: #1143

**Comment by Tonitohoru** [comment] 2021-03-06 20:52
Are there any other workarounds? Like another operating system? Or something else than mono idfk...

**Comment by ORelio** [comment] 2021-03-07 15:31
See https://github.com/ORelio/Minecraft-Console-Client/issues/1143#issuecomment-661274721 Also you may try Windows with .NET framework and see if it works better.

**Comment by Tonitohoru** [comment] 2021-03-08 13:26
My goal is to use linux for that. A windows server is just too expensive and I am using google cloud.
Now I downloaded this file https://www.youtube.com/watch?v=HglFM8GRzZA from Dexter.
I have switched from Debian to Ubuntu 16 and used mono 4.2.2 and it worked. 
I was able to join the sub server with it.
My only problem is: In this version the tasks.ini / script scheduler isn't working.
The top said it was version 1.12.2

Also is there another possibility? Like using something else to execute the file?

**Comment by Tonitohoru** [comment] 2021-03-08 13:31
Also tried with Debian just now. It's because of the client version. Older versions of console client don't have this problem

**Comment by Tonitohoru** [comment] 2021-03-08 13:46
Acutally it's fine. I am now using screen to dispatch commands i need

**Comment by ORelio** [comment] 2021-03-13 13:33
Glad you were able to sort it out somehow 👍

**Closed** 2021-05-21 18:14 UTC
Labels: a:bug, on:linux, resolved
