### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by techboy41** [ORelio/Minecraft-Console-Client#953] opened 2020-04-19 00:36 UTC
https://gyazo.com/93e2a8c13f12e2bfdb96ab50fe7ee971

I've been looking this issue up for a while and can't figure out the issue. I don't know a lot of code if any. Thanks.

**Comment by ORelio** [comment] 2020-04-19 15:08
Beware not to put unredacted access tokens into your screenshots, someone might be able to use it to log on a server as you. Closing as duplicate of #951.

**Closed by ORelio** 2020-04-19 15:08 UTC
