### ISSUE TITLE
Console crashes by AutoRelog

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#817] opened 2019-10-08 04:06 UTC
This error happens when the Sonsole lost connecting and try to relogin:

05:44:57 You are already connected to this proxy!
05:44:57 [MCC] [AutoRelog] Waiting 20 sec...
05:45:17 [MCC] [AutoRelog] Waiting 20 sec...
05:45:19 [MCC] [Script] respawn
05:45:21 [MCC] [Script] send /list
Connection lost.
05:45:21 [MCC] [AutoRelog] Waiting 20 sec...
Connection lost.
05:45:35 [MCC] [AutoRelog] Waiting 20 sec...
05:45:38 [MCC] [AutoRelog] Waiting 20 sec...
>
 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
 System.Collections.Generic.List`1.Enumerator.MoveNext()
 MinecraftClient.McTcpClient.Disconnect()
 MinecraftClient.Program.<>c__DisplayClass11_0.<Restart>b__0()
 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
 System.Threading.ThreadHelper.ThreadStart()

using:
[AutoRelog]
enabled=true
delay=20
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt

**Comment by Chtholly** [comment] 2019-10-29 04:58
it says [AutoRelog], but nothing happen, my account is still on and after the x seconds has gone mcc have some fail restarts

**Comment by JovonXandering** [comment] 2019-11-16 17:18
I dont think its your problem, i have this problem too.
The console client keeps trying to restart even when its already in a reconnect attempt, and then it just falls into an endless loop of restart and crashes
heres a video, cuz its hard to explain
https://imgur.com/a/6yKMBVw
I look around and i think it's caused by McTcpClient.cs line 358

**Comment by Chtholly** [comment] 2019-11-23 16:07
hmmm yea, should be the TimeoutDetector

**Comment by ORelio** [comment] 2019-11-24 11:51
Hello, thanks for reporting the issue and suggesting the cause, I think that indeed the TimeoutDetector might conflict with AutoRelog although I could not reproduce it on my side. Just pushed a fix, could you try it out and tell if it resolves your issue or not?

**Comment by Chtholly** [comment] 2019-11-25 21:11
Nope, nothing have changed.

**Comment by MightyPiggie** [comment] 2019-12-08 07:14
I am also on the latest version and I am also having this problem.

**Comment by ORelio** [comment] 2019-12-08 19:14
Thanks @MightyPiggie you stack trace gives more information. The interesting part being
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List1+Enumerator[T].MoveNextRare () [0x00013] in <285579f54af44a2ca048dad6be20e190>:0 at System.Collections.Generic.List1+Enumerator[T].MoveNext () [0x0004a] in <285579f54af44a2ca048dad6be20e190>:0
at MinecraftClient.McTcpClient.Disconnect () [0x00021] in :0
```
I'll look into this.

**Comment by ORelio** [comment] 2019-12-08 19:22
Indeed when a bot is loaded or unloaded while OnDisconnect() is being processed, it causes a crash.
Please try out the latest development build.

**Comment by MightyPiggie** [comment] 2019-12-08 19:34
Thanks, I will try it right now

> Indeed when a bot is loaded or unloaded while OnDisconnect() is being processed, it causes a crash.
> Please try out the latest development build.

**Comment by MightyPiggie** [comment] 2019-12-08 20:27
So it kinda works now. It doesn't crash atleast but it isn't working as it should.

Ah it still crashes but only after a while. I have no idea what happend this time so heres the log.

https://pastebin.com/XwQRW0h3

**Comment by ORelio** [comment] 2019-12-08 21:28
OK, found both issues.
 - Crash was caused by trying to send a message while disconnected. Likely caused by one of your script. Added better handling for the encountered exception so that it does not crash MCC.
 - Strange behaviour was caused by AutoRelog being triggered twice. Once when disconnected, and a second time when AutoRelog itself restarts MCC due to an additional event added in commit aaf1e8311bd672354b71fbad8a896475b56e89ca for catching manual disconnections. Now AutoRelog will ignore that additional event.

**Comment by Chtholly** [comment] 2019-12-08 21:45
Yea, now it works fine :D Thanks

**Comment by MightyPiggie** [comment] 2019-12-08 23:38
Yeah it seems to be fixed. I will post a update tommorow if its still working.

**Comment by MightyPiggie** [comment] 2019-12-09 06:14
Yup, its still working. So this issue has been resolved. Thank you again!

**Closed** 2019-12-09 20:30 UTC
Labels: a:bug, in:auto-relog, resolved
