### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by alicenchains** [ORelio/Minecraft-Console-Client#591] opened 2018-11-10 22:23 UTC
I'm using MCC to have several accounts on at the same time for a server. They usually run between 0.5% and 2.0% per instance. However after I get around 15-25 accounts on, some of the instances jump from 0.5% to a max of 30%, usually only 3 out of 20 of them reach 30% until my CPU maxes out and it starts force closing the applications one-by-one until the CPU is stable enough. However after I close 1 of the high CPU instances, one of the lower ones takes its place and jumps to 30%. It continues to do this until I close nearly all of the instances. I have 8gb's of ram so I should be able to handle the 30 accounts I anticipated without a problem. 

I also use Vultr VPS and I host an additional 30 accounts. Now, I pay for only a 2048mb VPS and it gets to about 30 accounts before the CPU starts maxing out and kicking random accounts. The server uses ubuntu so I can use screen with it instead of opening 30 different instances. 

I disabled terrainandmovements and loaded all of the accounts and it was a lot less ram, however with that set to false my bots inventories no longer work. What i mean is, they don't pick up any items dropped at their feet while terrainandmovements is set to false. I use a /sell all script for a server so that doesn't help me.

So my questions are: 
How can I reduce the CPU usage?
Is it possible to use screen with MCC?
Is there an alternate way to log all of my accounts in easier, and them staying online?
Why doesn't my account pick up items while terrainandmovements is set to false?

**Comment by ORelio** [comment] 2018-11-15 19:20
Hi,

I have no idea why the CPU high usage, but you could try in different environments. For instance, you could check whether it is related to Mono by trying to launch your 30 accounts from a Windows OS with .NET framework. If the issue does not happen, then it means this has something to do with the underlying setup, otherwise the issue is definitely somewhere in MCC.

Regarding item pickup. The server automatically places item in inventories of nearby players. However, by default, MCC never sends "location updates" packets because it has no idea of its surroundings. I guess that the server will process nearby items only on location updates, so nothing happens when no location updates are sent. When you enable terrain and movement, MCC knows how to move and sends location updates, which ultimately fixes item pickup.

**Comment by wobby123** [comment] 2020-06-28 16:56
I have 15 open. 14 are on "hidden" using a system scheduler and one is just minimised so I can see the chat from people I have ignored on my main account. 

![Screenshot_1441](https://user-images.githubusercontent.com/28870540/85953462-5d396000-b968-11ea-949f-def9e2eb53e5.jpg)

As you can see a lot of them are using around 5-10% of my CPU. I have an i7-8750H 2.20GHz. Seems to only be an issue when using more of them as other people have stated.

I know this is just under 2 years old but the problem is still here...

**Comment by ORelio** [comment] 2020-06-28 18:11
Hi,
Regarding the features you mentioned:
`showxpbarmessages` should only skip displaying messages displayed on your XP bar, not sure what could cause high usage here
`terrainandmovements` definitely uses more CPU to handle all the terrain stuff
`playerheadicon` will load your skin once on launch to set it as icon, should not affect CPU afterwards
`scriptcache` will store a compiled copy of each script when you launch it. Should slightly increase memory usage.
However I do not have any more suggestions for you as I'm not sure either what is causing high CPU usage when terrain is disabled.

**Comment by wobby123** [comment] 2020-06-29 08:10
> Hi,
> Regarding the features you mentioned:
> `showxpbarmessages` should only skip displaying messages displayed on your XP bar, not sure what could cause high usage here
> `terrainandmovements` definitely uses more CPU to handle all the terrain stuff
> `playerheadicon` will load your skin once on launch to set it as icon, should not affect CPU afterwards
> `scriptcache` will store a compiled copy of each script when you launch it. Should slightly increase memory usage.
> However I do not have any more suggestions for you as I'm not sure either what is causing high CPU usage when terrain is disabled.

Hi, I don't need more suggestions as changing what I said fixed it. I don't know why it did either but it did.

**Comment by CrewParzi** [comment] 2020-07-03 14:52
I have a similar problem, when the mc server restarts, all the alts are sent back to hub and I have anti afk setup with command to join back but for some reason when they get kicked the cpu usage becomes 100% and it stays at 100% till I close it and open them again.

**Comment by ORelio** [comment] 2021-05-21 17:24
Closing as we could not reproduce the issue.

**Closed by ORelio** 2021-05-21 17:24 UTC
Labels: a:bug, on:linux, waiting-for:more-info
