### ISSUE TITLE
Not moving at all

### ISSUE THREAD

**Issue by RPMYT** [ORelio/Minecraft-Console-Client#618] opened 2018-12-31 04:00 UTC
The player doesn't move - with /move, pushing, hitting anything, it just doesn't move. Using the latest version with movement enabled.

**Comment by Mhowser** [comment] 2018-12-31 04:08
/move does not work in 1.13+ versions due to the new world format Mojang
implemented.

**Comment by RPMYT** [comment] 2018-12-31 04:14
Is that fixable?

**Comment by Mhowser** [comment] 2018-12-31 07:34
As far as I know, no one is actively working on it.

**Comment by TheSnoozer** [comment] 2018-12-31 13:08
Is this only a problem for 1.13?

See: https://github.com/ORelio/Minecraft-Console-Client/issues/599

**Comment by Mhowser** [comment] 2018-12-31 14:50
Like you mentioned earlier on that issue, it isn't easy to implement that
specific terrain handler due to the different coding language used.

It all boils down to being too difficult to add support for 1.13 terrain,
especially since @ORelio doesn't have the time to work on this project like
he used to.

Hopefully in the near future we can see some noteworthy progress towards
1.13 terrain handling.

**Comment by TheSnoozer** [comment] 2019-02-03 01:53
Since I believe this is a duplicate of #599 i'm closing it.
If this is not the case, please feel free to reopen it, with further comments what versions are affected, so we can reproduce the issue.

**Closed by TheSnoozer** 2019-02-03 01:53 UTC
Labels: rejected:duplicate
