### ISSUE TITLE
Incorrect slot IDs set by WindowItems 

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1011] opened 2020-05-22 14:39 UTC
**Bug description**
The item slot ID set by WindowItems seems like is wrong.
Please see the screenshot. (The SetSlot handler was disabled for testing)
![image](https://user-images.githubusercontent.com/39955851/82677489-b253c900-9c7a-11ea-9977-3dea4b34eacc.png)
The slot ID after 9 seems like shifted 2 slot backward.
This is my how my inventory actually look like in-game
![image](https://user-images.githubusercontent.com/39955851/82678474-41adac00-9c7c-11ea-87e9-e0b6552fe4ae.png)
_Slot ID - from wiki.vg_
![image](https://wiki.vg/images/1/13/Inventory-slots.png)
Not sure what cause the problem (server or client)

I will do some further testing when I have time.

**Comment by ReinforceZwei** [comment] 2020-05-24 06:45
Not sure what happened. The MCC built from my laptop and from my desktop gave me different results.
The one from desktop seems fine, but the one from laptop have the above issue.
Maybe I am using different VS version and cause the issue. (desktop is using VS2017 while laptop is using VS2019)
I will close the issue first.

**Comment by ReinforceZwei** [comment] 2020-05-24 07:00
Ok nvm, the problem still exist. Need to watch very carefully from those console output to spot the error.

**Comment by ReinforceZwei** [comment] 2020-05-25 03:29
I post a new screenshot for better showing what is going on.
Lines start with `**` are printed from `OnWindowItems()`, which is received from `WindowItems` packet.
Lines without star are printed from `OnSetSlot()`, which is received from `SetSlot` packet.
![image](https://user-images.githubusercontent.com/39955851/82774269-e98ec980-9e76-11ea-8af8-f280bd8c5de7.png)
The inventory item received from `WindowItems` are not correct. 

Seems like somehow the elements in the array are shifted when we read them from the packet and causing the item being in the wrong slot. 

Also I noticed that the for-loop here in [`Protocol18.cs` line 553](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L553)
![image](https://user-images.githubusercontent.com/39955851/82775193-95391900-9e79-11ea-9632-aded7407dda5.png)
When I change the `<` to `<=`, I expected it should throw an `out of index/range` error but in fact it doesn't. Dose it mean the length of the array is longer than `element`?

Similar issue #1022

**Comment by ReinforceZwei** [comment] 2020-05-25 07:39
I used a Node.JS [Minecraft protocol library](https://github.com/PrismarineJS/node-minecraft-protocol) that parse and handle every packet nicely. I printed out the `WindowItems` packet and found that every is normal.
![image](https://user-images.githubusercontent.com/39955851/82789665-3f766800-9e9d-11ea-8e0e-5412baea8943.png)

So the problem must be somewhere in the MCC packet handling.

**Comment by ORelio** [comment] 2020-05-25 10:31
I noticed this when implementing click item but thought it was caused by some anti-cheat plugin to confuse bots (I was testing out an inventory generated by a Captcha plugin). You're having this in Minecraft vanilla without any plugin, right?

One big difference between [Window Items](https://wiki.vg/Protocol#Window_Items) and [Set Slot](https://wiki.vg/Protocol#Set_Slot) is that Set slot explicitly states the slot ID whereas Window Items implicitly uses the position in array as slot ID. Additionally, Set slot will set a single slot, so any leftover data will be discarded, whereas Window Items will read slots sequentially, so any leftover data may cause a shift in slots.

My guess would be that `ReadNextItemSlot()` is not properly skipping empty slots and/or slot NBT, causing a shift when reading sequential slot data. In your example, something in the Arrow stack for slot 9 is leftover and interpreted as an empty slot 10, then slot 10 is interpreted as slot 11, and so on.

**Comment by ReinforceZwei** [comment] 2020-05-25 10:55
About the `ReadNextSlot()`, I have tried parsing the packet by using individual method (`ReadNextBool()`,etc) and the result is the same as using `ReadNextSlot()`.

About the server I have used for testing, it does have some plugins installed, but I don’t think those would cause the issue. 

I will test again when my own server is available. (currently using laptop to work)

**Comment by Nekiplay** [comment] 2020-05-25 14:11
**mcversion=auto**
![image](https://user-images.githubusercontent.com/35975332/82820326-60e64c80-9ebb-11ea-9883-d1471894b4ba.png)

**mcversion=1.12.2**
![image](https://user-images.githubusercontent.com/35975332/82820390-81160b80-9ebb-11ea-8006-a4e94b1382ef.png)

**Comment by ReinforceZwei** [comment] 2020-05-25 15:47
@ORelio  I probably found the cause of the problem.

Item with no NBT are not handled correctly, leaving the 0x00 (TAG_End) behind and causing the next `ReadNextBool()` to determine the slot is empty. And hence the slots are shifted.

The root of cause is the `Queue.Peek()` method at [dataTypes](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/DataTypes.cs#L405). This method does not remove the element from the queue so that the TAG_End is left behind. ([docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.queue.peek?view=netcore-3.1)) Issue was solved after adding a `Queue.Dequeue()` before returning.

What a simple bug, but difficult to find 😆

**Comment by ORelio** [comment] 2020-05-25 18:08
Thanks, merged you pull request. So it was indeed a bug in NBT handling after all.
@Nekiplay Please try out again to see if your inventory is properly handled now 😄

**Comment by Nekiplay** [comment] 2020-05-27 02:06
mcversion=auto
![image](https://user-images.githubusercontent.com/35975332/82969198-8329b880-9fe8-11ea-96a0-c65330cec8ab.png)

mcversion=1.12.2
![image](https://user-images.githubusercontent.com/35975332/82969174-72794280-9fe8-11ea-9463-8ab7a52009b3.png)

**Comment by ORelio** [comment] 2020-05-27 10:29
OK, so apparently it's still not fixed.

**Closed** 2020-12-24 17:47 UTC
Labels: a:bug, in:inventory-handling
