### ISSUE TITLE
Unable to connect to 1.7.10 server

### ISSUE THREAD

**Issue by MCwenka** [ORelio/Minecraft-Console-Client#1199] opened 2020-08-12 14:49 UTC
I tried to connect to a 1.7.10 server.
When I start the program,When the server is successfully connected, it says "Because Exception.ToString () failed to print the exception string". Then let me click OK and terminate the program.
But it did connect to the server successfully. When I terminated the program, the corresponding user would disconnect from the server...

**Comment by MCwenka** [comment] 2020-08-12 14:49
The IP address of this server is: `yd.lcjm.club`

**Comment by ReinforceZwei** [comment] 2020-08-12 15:15
Please copy and paste the full console output to here so that we could have more information about the problem.

**Comment by MCwenka** [comment] 2020-08-12 16:06
> Please copy and paste the full console output to here so that we could have more information about the problem.

This is all the output of the console: [Log.txt](https://github.com/ORelio/Minecraft-Console-Client/files/5064035/Log.txt)

**Comment by ReinforceZwei** [comment] 2020-08-12 16:27
For some reason your MCC cannot print out the error message so I tested it myself and got the error message.
```
未處理的例外狀況: System.IO.InvalidDataException: Failed to process incoming packet of type ChatMessage. (PacketID: 2, Protocol: 5, LoginPhase: False, InnerException: System.InvalidOperationException). ---> System.InvalidOperationException: 佇列是空的。
   於 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   於 System.Collections.Generic.Queue`1.Dequeue()
   於 MinecraftClient.Protocol.Handlers.DataTypes.ReadNextByte(Queue`1 cache) 於 C:\Users\reinforce\source\repos\Minecraft-Console-Client-master\MinecraftClient\Protocol\Handlers\DataTypes.cs: 行 312
   於 MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData) 於 C:\Users\reinforce\source\repos\Minecraft-Console-Client-master\MinecraftClient\Protocol\Handlers\Protocol18.cs: 行 281
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData) 於 C:\Users\reinforce\source\repos\Minecraft-Console-Client-master\MinecraftClient\Protocol\Handlers\Protocol18.cs: 行 935
   於 MinecraftClient.Protocol.Handlers.Protocol18Handler.Update() 於 C:\Users\reinforce\source\repos\Minecraft-Console-Client-master\MinecraftClient\Protocol\Handlers\Protocol18.cs: 行 156
   於 MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater() 於 C:\Users\reinforce\source\repos\Minecraft-Console-Client-master\MinecraftClient\Protocol\Handlers\Protocol18.cs: 行 131
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
```
_佇列是空的 mean empty queue_

**Comment by ORelio** [comment] 2020-08-12 20:05
Indeed, 1.7.X has Chat message only while 1.8.X and greater have message position:

https://wiki.vg/index.php?title=Protocol&oldid=6003#Chat_Message
https://wiki.vg/index.php?title=Protocol&oldid=7368#Chat_Message

However, MCC attempts to read the position regardless of the version and catches the `ArgumentOutOfRange` exception. The exception type changed to `InvalidDataException` when changing the List to Queue in 06714423a3280801949091d67a57abb2aaff7164, thus introducing the bug. Fixing by replacing the try/catch with a proper check for Minecraft 1.8 like for other packets.

**Comment by MCwenka** [comment] 2020-08-13 01:18
> Indeed, 1.7.X has Chat message only while 1.8.X and greater have message position:
> 
> https://wiki.vg/index.php?title=Protocol&oldid=6003#Chat_Message
> https://wiki.vg/index.php?title=Protocol&oldid=7368#Chat_Message
> 
> However, MCC attempts to read the position regardless of the version and catches the `ArgumentOutOfRange` exception. The exception type changed to `InvalidDataException` when changing the List to Queue in [0671442](https://github.com/ORelio/Minecraft-Console-Client/commit/06714423a3280801949091d67a57abb2aaff7164), thus introducing the bug. Fixing by replacing the try/catch with a proper check for Minecraft 1.8 like for other packets.

Thank you for your help. I can log in to the server normally now. But it seems that if someone else logs in or leaves the server, (`xxxx joined the game` or `xxxx left the game`) the same error will be triggered. Even if I as like as two peas, the output of the console is exactly the same as that of the last `debugmessages=true.`

**Comment by ORelio** [comment] 2020-08-13 08:39
I could not reproduce your crash on a 1.7.10 server jar in offline mode:

![image](https://user-images.githubusercontent.com/1128206/90112867-d80bde00-dd50-11ea-8c24-5b5e32a4d301.png)

Could you provide a server IP demonstrating the issue?

**Comment by ReinforceZwei** [comment] 2020-08-13 08:43
@ORelio He did provided a server address: `yd.lcjm.club`

**Comment by ORelio** [comment] 2020-08-13 08:49
@ReinforceZwei My bad 😅

**Comment by ORelio** [comment] 2020-08-13 13:26
Sorry but I was not able to reproduce.

![image](https://user-images.githubusercontent.com/1128206/90139722-06051880-dd79-11ea-8b28-f3372fff6fa0.png)

If you manage to get a stack trace, please post it.

**Comment by ReinforceZwei** [comment] 2020-08-13 13:30
@ORelio Need another user to join the server to trigger the bug.
![image](https://user-images.githubusercontent.com/39955851/90140159-eaffcc00-ddab-11ea-84e2-bb0dd556d8d1.png)
_佇列是空的 mean empty queue_

**Comment by ORelio** [comment] 2020-08-13 21:06
Thanks @ReinforceZwei, I was not able to log two accounts at the same time. So the culprit is the Update Score packet (ID 60, 0x3A):

https://wiki.vg/index.php?title=Protocol&oldid=6003#Update_Score
https://wiki.vg/index.php?title=Protocol&oldid=7368#Update_Score

In 1.8, the last field is optional, but in 1.7 the last _two_ fields are optional, hence the error. MCC did not properly implement that.

**Comment by ORelio** [comment] 2020-08-20 12:13
I'll close the issue as resolved. Feel free to reopen if you still encounter packet handling issues on 1.7.X.

**Closed by ORelio** 2020-08-20 12:13 UTC
Labels: a:bug, in:protocol-compatibility, resolved

**Comment by MCwenka** [comment] 2021-01-16 15:24
Hello, I have a similar problem

This is the same server, the same game version (1.7.10). When I successfully connected to the server, the program crashed. These are the console outputs:

[] Welcome Boz to zc, owned by ouououy.
[] Boz joined the game.

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.Protocol.Handlers.PacketPalettes.PacketTypePalette.GetInco
mmingTypeById(Int32 packetId)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 pac
ketID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
