### ISSUE TITLE
Can't receive text from Cauldron 1.7.10 server

### ISSUE THREAD

**Issue by laysdra7265** [ORelio/Minecraft-Console-Client#88] opened 2015-07-29 12:29 UTC
well,when I use this client(version 1.8.2) login to a cauldron-1.7.10-2.1403.1.54(no install mod) and a KCauldron-1.7.10-1481.148(has install mod) Server
It connected success but it didn't show any text from server.
And what stranger is that the server didn't list the player login with this client(But still can send command or chat)
and it seems that the server didn't generate the player entity 
when I quit ,the server show the error about bad packet id 64
How can I solve this problem? 
Is is a awesome client,I hope use it on our server for op.> <please help!!

(and sorry for my bad english...

![qq 20150729202119](https://cloud.githubusercontent.com/assets/10185394/8957313/5168c916-3630-11e5-9397-f2fab295f42a.png)

**Comment by ORelio** [comment] 2015-07-29 18:54
Hello,
Cauldron seems to be an [abandoned project](http://cauldron.minecraftforge.net/threads/downloads-removed-working-on-sponge-1-8.780/).
Their authors are encouraging to use [Sponge](https://www.spongepowered.org/) instead.
The Cauldron server software seems to contain forge AND bukkit.
Maybe it is performing some advanced checks to detect if the client is either a vanilla client or forge.
But since MCC is not a vanilla client nor forge, cauldron does not work properly with MCC.
I'd like to try it out, to see if there can be an easy fix, but download links were removed for Cauldron.
If there is an easy fix for this issue, I have no problem applying it.
Do you have any download link for this?

**Comment by laysdra7265** [comment] 2015-07-30 10:19
Althrough Cauldron official website remove all download ,here is still have
the download link of all version of Cauldron on the internet
Here are two link

This one only has the Couldron download link :
http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10/

This one has all of third-party server download mirror :
http://tcpr.ca/cauldron

Since Cauldron is not update anymore,the latest version might be outdate .
The forge version is too low that some mod can't install. :(
So it seems that there is someone keep develop the Cauldron and rename it
to KCauldron.

here is git and official website:
https://gitlab.prok.pw/Prototik/KCauldron

and here is download area(Not official,but can get the complete latest
version archive which can be use immediately .):
http://tcpr.ca/kcauldron

Something you should notice is that KCauldron is very similar to Cauldron,
but not completely the same .
Althrough the feature and function is same,KCauldron has a little different
that may cause compatibility problem.
I suggest that not only test client on vauldron but also on KCauldron.

**Comment by ORelio** [comment] 2015-07-30 15:26
Thanks for the download links.

After some tests, it seems like messages are not sent at all by the server.
Tried sending a [Client_Settings](http://wiki.vg/index.php?title=Protocol&oldid=6003#Client_Settings) packet to tell the server that chat is enabled, without success yet.

I guess I'd need to dig Cauldron's source code to figure out what it is expecting from the client before "finalizing" its login phase because obviously it's waiting for something that a vanilla or bukkit/spigot does not requrie and which is not mentioned on the protocol wiki as well.

But unfortunately, that's not really easy since [source code was deleted](https://github.com/MinecraftPortCentral/Cauldron)...

So sorry but currently this is not really easy to fix :/

**Comment by laysdra7265** [comment] 2015-07-30 16:11
oh…why don't you consider about KCauldron ?It has source code and I think
it will displace cauldron in the feature(Our server is useing
KCauldron，because of Cauldron's forge is outdate)
and i think that protocol work on KCauldron may work on Cauldron(Because
they are really similar.We use KCauldron instead of Cauldron.All plugin
from Cauldron and mod are working fine)
I guess KCauldron's source code must  base on Cauldron's source code.:)
2015/7/30 下午11:26於 "ORelio" <notifications@github.com>寫道：

**Comment by ORelio** [comment] 2015-07-30 16:20
Well, good idea, will examine KCauldron instead!

**Comment by laysdra7265** [comment] 2015-07-30 23:29
Ops…I can't believe that it just restore few days ago,and now it is down again.
Thankfully there is someone make a backups.
:/

**Comment by ORelio** [comment] 2015-07-31 10:06
Didn't find something really useful while browsing source code, so I tried another approach: connect with a vanilla client to analyze which packets are sent by the vanilla client. But now I realize that I can't connect to the cauldron server `cauldron-1.7.10-2.1403.1.54-server.jar` using a vanilla `1.7.10` minecraft, getting stuck indefinitely on the `Logging in...` screen. What a weird server. Server-side nothing more than a "INFO: UUID of player ORelio is [...]".

(Cauldron definitely isn't an easy fix xD)

**Comment by laysdra7265** [comment] 2015-07-31 12:20
Oh…it looks like because of client isn't install forge?
This weird server-side log is same as the result of using console client.

**Comment by laysdra7265** [comment] 2015-07-31 12:29
Although console client can't get the respond text from server, but still
can send command.
It seems that this weird situation  make the player safe because server
doesn't generate the entity of player.
I hope I have time to take a look of protocol of server,it looks
interesting.:)

**Comment by ORelio** [comment] 2015-07-31 12:35
Ah, Forge is required?
Cannot connect with vanilla?
Because forge is *not* supported, see issue #9 ^^"

**Comment by laysdra7265** [comment] 2015-07-31 14:58
Ops…I didn't notice that.

This is project is awesome and useful.
I believe it will getting better and better.

I am interesting in this project ,but so sad I just learned java and I
don't have too much free time.
It will be more useful if it can connect to forge server.

I have an idea.
Is it will be more easy to implement forge console client if I get the
source code of forge client and just remove all the function except chat
feature?

I know where to get forge source code(the forge source code include
minecraft source code.) ,because I have learn a little about forge modding.

Hope this will help you.^ ^
(The link of forge source code will give you later…

**Comment by Aragas** [comment] 2015-07-31 17:53
Client first sends all installed mods. If there is something wrong, server sends correct mods list and kicks. You must get that info and connect second time, correct?

**Comment by ORelio** [comment] 2015-07-31 20:16
Yes. See #9 for more details. laysdra7265: Not sure taking code from Forge would require less work. So you can confirm that Cauldron requires Forge on the client?

**Comment by laysdra7265** [comment] 2015-07-31 23:30
Cauldron and KCauldron are Forge server.
Because forge has its own protocol,I think it must need forge client.
 

And I found out that the source code of KCauldron isn't include the part of forge and minecrft .

So you need to get those missing class in the forge source code.

**Comment by laysdra7265** [comment] 2015-08-01 01:17
If you use forge server,you will need install forge in client.
If you install mod on forge server, you need to install same mod on forge client .

**Comment by ORelio** [comment] 2015-08-01 12:44
Ok, so the issue is that Forge isn't supported, not Cauldron itself.

**Comment by ORelio** [comment] 2016-02-27 17:46
Forge should be handled now as of #100 and further fixes were added eg as of #117
The issue should be fixed, but feel free to reopen if needed ;)

**Closed by ORelio** 2016-02-27 17:46 UTC
