### ISSUE TITLE
Crash on MC 1.7 server join w/ terrain enabled

### ISSUE THREAD

**Issue by imaBASKET** [ORelio/Minecraft-Console-Client#179] opened 2016-08-13 04:00 UTC
When I join a specific server with terrain enabled, the client crashes as soon as it connects with this error:

http://hastebin.com/viqoqaficu.avrasm
When terrain isn't enabled it does not crash.

IP: pvp.vaelox.com

**Comment by Pokechu22** [comment] 2016-08-13 04:08
Are you in the end?  If so, try updating to the latest beta build - see #173 regarding the end (it's related to skylight)

**Comment by imaBASKET** [comment] 2016-08-13 10:12
@Pokechu22 No I am not in the end, I am also on the latest version.

**Comment by ORelio** [comment] 2016-08-14 19:26
Will try to reproduce. Thanks for your report.

**Comment by ORelio** [comment] 2016-08-21 10:18
After some investigations that's because terrain and movements was not implemented for 1.7 but is enabled with 1.8+ support on 1.7 servers, hence the crash. Will investigate further terrain changes between 1.7 and 1.8 to see if I can add support for 1.7 terrain.

**Comment by ORelio** [comment] 2016-08-21 13:47
Terrain and movements are now fully implemented for Minecraft 1.7, resolving the issue :)
You can grab the latest development build and feel free to reopen if needed.

**Closed by ORelio** 2016-08-21 13:47 UTC
