### ISSUE TITLE
Using terrainandmovements from a C# script seems to be blocking on main thread.

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#251] opened 2017-03-02 08:34 UTC
It makes everything freeze, including other scripts, until it is finished.

**Comment by ORelio** [comment] 2017-03-02 09:19
I don't understand your issue. What are you tying to do?

**Comment by theonlygusti** [comment] 2017-03-02 10:38
I am just experimenting at the moment.

I am running two C# scripts from login, one of them starts a stopwatch and every time its `Update` method is called it prints the number of milliseconds since it started.

The second script, every 2 seconds, moves the player to a random block within 5 blocks' distance.

Whenever the second script is running, the first script is paused and doesn't log again until after the second script finishes (what I assume is) its pathfinding, or heavy-thinking.

This means that when the first script does next log, it has been paused for a significant amount of time and the difference between the millisecond counter in this log and the previous log is much greater than any previous.

**Comment by ORelio** [comment] 2017-03-03 09:12
Oh, I see. For consistency reasons pathfinding is done on the main thread, because terrain being modified while path is calculating would cause bad things. You should not call pathfinding too often, or at least let it breathe a while so that the client can catch up with network events.

**Comment by theonlygusti** [comment] 2017-03-03 15:58
What about suspending only other terrainandmovement calls while path finding is being done? And allowing other scripts that don't make use of it to continue unhindered?

**Comment by ORelio** [comment] 2017-03-03 17:07
Because consistency issues are not only due to other plugins, but also when receiving terrain data from the server while processing pathfinding. Can't do both at the same time.

**Comment by theonlygusti** [comment] 2017-03-03 22:22
Is it possible to use our own pathfinding algorithms? All I want to do is move in a random straight line, max length 5. I don't think that should take a noticeable length of time to complete.

But yeah, I understand now why it would have to run on the main thread, that makes sense.

**Comment by ORelio** [comment] 2017-03-04 13:53
Yes you can do your own, lighter pathfinding. MCC's default pathfinding is [A*](https://en.wikipedia.org/wiki/A*_search_algorithm#Example) but if you have specific needs you can access terrain data and do your own processing with the world from [GetWorld()](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L577), then perform one-block movements, one at a time. Not sure there is a ChatBot method for that but it can be added, and as a workaround you can at least use "/move" commands.

**Comment by ORelio** [comment] 2017-03-13 21:16
Ok so this issue is a duplicate of #219, closing this one, leaving the other open.

**Closed by ORelio** 2017-03-13 21:16 UTC
