### ISSUE TITLE
1.13 Support?

### ISSUE THREAD

**Issue by hashdashme** [ORelio/Minecraft-Console-Client#532] opened 2018-07-28 10:16 UTC
Hi, just wondering when this will support 1.13

# Thanks

**Comment by ORelio** [comment] 2018-07-31 18:13
Unfortunately I have less and less time available to upgrade MCC for each Minecraft version. Any contribution is welcome!

**Comment by ORelio** [comment] 2018-07-31 18:17
Closing this thread as duplicate of #525

**Closed by ORelio** 2018-07-31 18:17 UTC
