### ISSUE TITLE
I cant connect to a 1.8 server

### ISSUE THREAD

**Issue by PublicHumiliation** [ORelio/Minecraft-Console-Client#261] opened 2017-03-19 15:51 UTC
When I try to connect to Saico pvp I join the server and it says outdated client please upgrade. Any ideas?

**Comment by Pokechu22** [comment] 2017-03-19 16:00
Duplicate of [some of the information later found in #227](https://github.com/ORelio/Minecraft-Console-Client/issues/227#issuecomment-286539081): update to [the latest dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by PublicHumiliation** [comment] 2017-03-19 20:31
How would I get the settings and stuff for the dev build all it does is log into the main thing

**Comment by PublicHumiliation** [comment] 2017-03-19 20:36
And now it is saying https://gyazo.com/258925eea6e7116a787d34271978f86a

**Comment by ORelio** [comment] 2017-03-19 20:38
Settings INI file is automatically generated. On this error simply type server version and press return.

**Comment by ORelio** [comment] 2017-03-19 20:39
Also server IP is `saicopvp.com` not `play.saicopvp.com` according to their website.

**Comment by PublicHumiliation** [comment] 2017-03-19 20:51
Alright thank you

**Comment by PublicHumiliation** [comment] 2017-03-19 21:30
Do you also know how to turn anti afk on or access the files of the updated version?

**Comment by PublicHumiliation** [comment] 2017-03-19 23:15
never mind I got it all figured out

**Comment by ORelio** [comment] 2017-04-17 13:28
Since the issue seems resolved, I'm closing it. Feel free to reopen if needed.

**Closed by ORelio** 2017-04-17 13:28 UTC
